### ISSUE TITLE
Access to phpmyadmin

### ISSUE THREAD

**Issue by umeshnevase** [rtCamp/easyengine#12]
From where can we access phpmyadmin?

**Comment by jdiaz1302** [comment]
Hi, what credentials should I use to access phpMyAdmin?

**Comment by pixeline** [comment]
@jdiaz1302 I was wondering the same. Saw [this](http://community.rtcamp.com/t/username-and-password-for-phpmyadmin/5453)

**Comment by jdiaz1302** [comment]
Thanks! Actually that was my first guess and did try it but it didn't work :P Will try again, maybe I copied a blank space or something, thanks!
