### ISSUE TITLE
Launchpad PPA Repos

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#130]
TODO: 

#### For Nginx

- [x] Create own launchpad repo for nginx with purge module as https://launchpad.net/~brianmercer/+archive/nginx doesn't support Ubuntu 13/14
- [x] Add nginx build with pagespeed module
- [x] Add http://wiki.nginx.org/HttpSubsModule
- [x] Add support for Lua

**Comment by gau1991** [comment]
In latest build we added support for Lua also.
