### ISSUE TITLE
database for easyengine

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#139]
As of now we are relaying on conventions and it will continue to work.

But at some point in future, we need to use a database. This task is to collect relevant links and pointers. So when time will come, we will have homework done!

### Database Candidates
- sqlite 3 [fast, lightweight]
- mongodb [web-based version in future may use mongodb]
- mysql [already installed, used by wordpress and other tools, familiar]

### Links
- sqlite and bash - http://andreaolivato.tumblr.com/post/133473114/using-sqlite3-in-bash
- compare mongo & sqlite - http://db-engines.com/en/system/MongoDB%3BSQLite

**Comment by rahul286** [comment]
Update: We added sqlite support in EE 3.x

**Comment by sagargulati** [comment]
When can we expect MongoDB?
