### ISSUE TITLE
Problem with ee edit & sensible-editor

### ISSUE THREAD

**Issue by Mermouy** [rtCamp/easyengine#172]
I have problems with some terminal console (actually on manjaro/arch) I don't know if it comes from the system which doesn't recognize this alias (sensible-editor), anycase better to avoid such possible problem don't you have any?

Ps: I know easyengine is for debian based but it happen to me when connecting via ssh, we should be able to edit file from any system!
Must be verified... (maybe a just misconfiguration from my system?)

**Comment by rahul286** [comment]
@Mermouy is your problem solved? If it persists with EE 3.x, please let us know.
