### ISSUE TITLE
HipHop Support

### ISSUE THREAD

**Issue by duajanuari** [rtCamp/easyengine#180]
Hi, 

It seems HipHop support is nice, they have prebuilt packages, and perform quite better than php5-fpm. Not much changing codes I guess.

Here, take a look at this: https://github.com/facebook/hhvm/wiki#installing-pre-built-packages-for-hhvm

**Comment by jmn00** [comment]
@rahul286 I set up another install and this time hhvm performance did not hinder cached page loads, even with W3TC running. Now running hhvm on my personal blog without issues. Uncached pages are loading ~1sec or less, with cached pages ~500ms on average. That's fast. Think I'll stick with hhvm for now.

As it happens, I tested mod_pagespeed with this setup per [rt tutorial] (https://rtcamp.com/tutorials/nginx/using-pagespeed/) and found slight improvements though it failed to combine javascript and css files (and yes, I uncommented those filters and tested with W3TC uninstalled). I'm keeping mod_pagespeed on for now but using W3TC to combine css and js.

**Comment by pnommensen** [comment]
afaik, PHPMyAdmin requires mysqli immediately, and HHVM still does not support this but will do further testing today.

**Comment by aristovia** [comment]
Fantastic!!! Installed HHVM with ee. Site powered by WordPress. I use plugin (PHP/MySQL CPU performance statistics) to test basic server environment performance.  For ee PHP-FPM (5.5.21-1+deb.sury.org~trusty+2) out of the box, general PHP Test time (for all tests ) was 12,66 seconds and PHP performance index was 790. After installing HHVM first run showed 4,83 seconds and performance index 2070. Second run showed even better results 1,22 seconds and and performance index 8197. I gues it's 11X better results :-) I'm surprisingly shocked 0_0 Results even outperform standart server results which plugin developers use to indicate if your server is fast or slow.

**Comment by rahul286** [comment]
@aristovia Thanks for sharing your experience. 

We hope to make HHVM as default in EE 3.1 :-)

**Comment by jmn00** [comment]
Are you including JIT (just in time compiler) configuration?

**Comment by MattyLB** [comment]
@Johnathan have you ran into those pesky "TC FULL" errors that end in HHVM
crashing and no FPM fallback? Its been happening to me about once a week as
the hhvm caches build and gives no warning signs. Has something to do with
the cache size parameters for various cacheing stages hhvm puts content
through as it ages, eg frozen, cold, etc.  I saw claims that raising memory
limits on a couple of the cache levels helped prevent the TC Full errors,
just not sure why and if they would work for an EE-based environment

Aside from this somewhat preventable issue, I've had zero problems with
hhvm using EE on standard and mu sites with several dynamic content
plugins. HHVM definitely has my vote once this is addressed

**Comment by w33zy** [comment]
Does anyone here notice HHVM's memory usuage slowly creeping upwards? I am running it one a new WP install I notice creeping past 65% memory usage.

**Comment by cssinf** [comment]
I have tried HHVM with mysql previously and it was working fine at ubuntu 14.04 but some time it crashes so not used for production site.
Today i tried using ee and HHVM together using 2GB linode debian 7. Ee is working fine without HHVm but when i add HHVm i get an error "Error establishing a database connection" usually this happen when our wp-config.php is missing the db details but as ee settings are used so no change in the db details.
i used these guides for the setting at Debian 7

Working fine
https://rtcamp.com/easyengine/
http://docs.rtcamp.com/easyengine/commands/site/create

Getting error on this part 
https://rtcamp.com/tutorials/php/hhvm-with-fpm-fallback/
https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Debian-7

**Comment by puikinsh** [comment]
I am testing EE 3.0.4 with HHVM 3.6 and I am having the same problem as @cssinf. However, I am using Ubuntu 14.04 and WordPress multisite and still getting "Error establishing a database connection". Log files aren't helping either.

**Comment by w33zy** [comment]
@cssinf there is an issue with the MySQL port used in the 3.6.0 release, you may want look at this
https://github.com/facebook/hhvm/issues/5002

**Comment by cssinf** [comment]
Dear @puikinsh and @w33zy  i have used this solution yesterday "wordpress' wpconfig.php file to use 127.0.0.1 instead of localhost." and wordpress was running fine but bit slow . i have to check why it is..I was busy with wp-types plugins which are not compatible with HHVM so forgotten to update here.
@w33zy Thank you for the info and help ..

**Comment by w33zy** [comment]
@cssinf can you keep and eye on the memory usage of hhvm with this new update? check to see if it is slowly creeping upwards.

**Comment by joeguilmette** [comment]
Oh how I wish this was moved to 3.0...

**Comment by cssinf** [comment]
Sure @w33zy i will let you know , but we have plenty of ram for hhvm to consume... 
I have to test https + HHVM + non compatible wordpress plugins ...
 https is too slow and in india we don't have any ec2 / linode / DO data centres ,gtmetric show 5sec + for both our website....

**Comment by rahul286** [comment]
Related to https://github.com/rtCamp/easyengine/issues/199

Final testing and discussion will be done on https://github.com/rtCamp/easyengine/issues/199

Please follow https://github.com/rtCamp/easyengine/issues/199

**Comment by rahul286** [comment]
@joeguilmette we hope to add it in 3.1

In 3.0 we were changing programming language so we avoided new features purposely. We did not want to break any old site.

**Comment by joeguilmette** [comment]
You guys are awesome. Keep up the fantastic work.

**Comment by semuk** [comment]
Hi..loving easy engine so far ..all works fine without HHVM but I really want to get it working
Ubuntu 14.04 Tested Easy Engine and can create sites 
Then Followed this https://rtcamp.com/tutorials/php/hhvm-with-fpm-fallback/
This package added for HHVM https://github.com/facebook/hhvm/wiki/Prebuilt-packages-on-Ubuntu-14.04
HHVM running but generating these errors so not working correctly
Unable to read pid file /var/run/hhvm/pid for any meaningful pid
command failed: "lsof -t -i :9000 | xargs kill -9"
command failed: "lsof -t -i :9000 | xargs kill -9"
Unable to start page server
Shutting down due to failure(s) to bind in HttpServer::runAndExitProcess
Unable to start page server
Shutting down due to failure(s) to bind in HttpServer::runAndExitProcess

Any Help would be greatly appreciated thanks...

**Comment by iShariefi** [comment]
How do I make HHVM fallback to php7.0-fpm?
