### ISSUE TITLE
lsb_release : command not found

### ISSUE THREAD

**Issue by RavanH** [rtCamp/easyengine#206]
On a fresh Debian Wheezy (logged in as root via ssh) the command 

```
curl -sL rt.cx/ee | bash
```

will produce the error:

```
bash: line6: lsb_release : command not found
EasyEngine (ee) Is Made For Ubuntu And Debian Only As Of Now
You Are Free To Fork EasyEngine (ee): https://github.com/rtCamp/easyengine/fork
```

So I would suggest starting right after #!/bin/bash with something like:

```
# Checking lsb_release
if [ ! -x  /usr/bin/lsb_release ]
then
    echo -e "\033[31mLsb_release Command Not Found\e[0m" | tee -ai $INSTALLLOG
    echo -e "\033[34mInstalling lsb-release, Please Wait...\e[0m" | tee -ai $INSTALLLOG
    apt-get -y install lsb-release &>> $INSTALLLOG || OwnError "Unable to install lsb-release"
fi
```

**Comment by jult** [comment]
apt-get install curl lsb-release
What sources are required for this? This doesn't work in a default debian wheezy..

**Comment by RavanH** [comment]
@jult they both are in the main source, see https://packages.debian.org/wheezy/curl and https://packages.debian.org/wheezy/lsb-release ... you should not have to add any special repositories for this.
