### ISSUE TITLE
Ubuntu 14.04 - phpapi-20121212+lfs

### ISSUE THREAD

**Issue by JosefJezek** [rtCamp/easyengine#215]
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php5-memcache : Depends: phpapi-20121212+lfs
 php5-xdebug : Depends: phpapi-20121212+lfs
E: Unable to correct problems, you have held broken packages.
[ Tue Apr 29 15:13:55 CEST 2014 ]  Unable To Install Nginx PHP5 MySQL Postfix

**Comment by robneu** [comment]
I don't think this is resolved. I'm still having issues with it.

**Comment by alandarev** [comment]
Still the same issue.
