### ISSUE TITLE
[enhancement] Insert "if" stub in site config 

### ISSUE THREAD

**Issue by rippler** [rtCamp/easyengine#219]
Perhaps this could be implemented as `--ir` (as in if-rules) or something like that.
ee could insert few marked-out examples for easy manual editing, such as by referrer, GeoIP, etc.

`# WPSINGLE BASIC NGINX CONFIGURATION`
`server {`
 `       if ($http_referer ~* "semalt\.com") {`
 `          return 444;`
 `       }`

**Comment by rahul286** [comment]
I think #352 will address this.

Please read that issue details, and if you think you need something different, add some details here so we can discuss your use case. :-)
