### ISSUE TITLE
Create directory for location of SSL certs

### ISSUE THREAD

**Issue by rippler** [rtCamp/easyengine#222]
I looked around but can't find it. I see* that for 22222 it's /var/www/22222/certs.
Can we assume that the same directory should be used for other sites?
Of course we can put it anywhere, but it's better to use a "standard" location.

* https://github.com/rtCamp/easyengine/blob/189c746772bb6061259dec59a61863a4d9059856/usr/share/easyengine/nginx/22222

**Comment by rahul286** [comment]
@rippler about my comment:

> It is not recommended to have a single page accessible over both – HTTP and HTTPS. Might create duplicate content issue in search engines

I meant HTTP should redirect to HTTPS or vice-versa. That takes care of bookmarks and other links. 

I do not see any benefit of allowing a page to be accessed on two different URLs.

**Comment by rahul286** [comment]
For certificates, we use `/var/www/example.com/cert/` but as other said, you can use any location. 

With letsencrypt.org, we hope to be able to add certificates automatically. So location may not be an issue.

Related - https://github.com/rtCamp/easyengine/issues/376
