### ISSUE TITLE
[enhancement] Input validation

### ISSUE THREAD

**Issue by rippler** [rtCamp/easyengine#224]
It's not a big deal, but in the future it'd be good to have basic input validation.

``root@www:~# ee site create --help``
``...``
``Successfully Created New Website: http://--help``
``root@www:~# ee site create %20ok``
``...``
``Successfully Created New Website: http://%20ok``

**Comment by rahul286** [comment]
We have added plenty of validation in ee 3.x. So we are closing this.

Please let us know if you find any issue in future.
