### ISSUE TITLE
Cookie Issue - Solution

### ISSUE THREAD

**Issue by shaneholloman** [rtCamp/easyengine#226]
I made a fresh Server instance with Ubuntu 14.04

Installed EE - all is good
Ran `ee site create 107.170.131.xxx --wpsubdomain --wpfc` - all is good
Went to login and got
`ERROR: Cookies are blocked or not supported by your browser` which definitely not the case for me

So Added this to the wp-config:
``` PHP
define('ADMIN_COOKIE_PATH', '/');
define('COOKIE_DOMAIN', '');
define('COOKIEPATH', '');
define('SITECOOKIEPATH', '');
```

This solved my issue - hope it helps someone else...

**Comment by rahul286** [comment]
@shaneholloman we never faced that issue but thanks for sharing your workaround. :-)

**Comment by RavanH** [comment]
Strange old issue but I'm facing it now too on a fresh new Ubuntu Xenial + latest easyengine on a Scaleway VPS running a multisite with multinetwork plugin. Sometimes (seems random) when logging in on any of the sites on the networks, I get this "cookies blocked" message.

The network is installed with the Redis option.

Will try to find out more and see if the cookiepath/domain fix does anything in my case.

**Comment by RavanH** [comment]
Found so far that this usually happens only the first time logging in to a newly created site on the network. Logging in a second time will work just fine. In the request and response headers I see respectively the expected Cookie and Set-Cookie headers. Including wordpress_test_cookie, wordpress_logged_in_ and all that... so that does not explain the error message :(

**Comment by RavanH** [comment]
OK, it happens not only the first time logging in to a new site, also when revisiting older site admins. And a second login is not needed, only refreshing the login.php page (that came back with the cookie error message) will get me to the dashboard... So it looks like the first login works fine on the background but still the error message is shown. Weird.
