### ISSUE TITLE
File / Folder Owner permission

### ISSUE THREAD

**Issue by hchouhan** [rtCamp/easyengine#227]
Hello,
I finally started using EE and just need to say that I love it. It's just too easy.
## UPDATE

Before installing EE, I had created a new user with root privileges. Now when I use it to connect with SFTP over SSH, I can view all folders, but unable to upload any files inside '/var/www/mywebsite.com/' or '/var/www/mywebsite.com/htdocs'. 

The error I get is "Insufficient privileges to perform the operation."

**Comment by gagomap** [comment]
@MiteshShah : If i force login via ssh key for all user, i can't use www-data to login sftp, even i added ssh key in .ssh (in /var/www folder).

**Comment by gagomap** [comment]
i have fixed it by added these lines sshd config file:

```bash
Match User www-data
PasswordAuthentication yes
```
