### ISSUE TITLE
Deletion is not working

### ISSUE THREAD

**Issue by hchouhan** [rtCamp/easyengine#230]
I used below command to delete a site

```
 sudo ee site delete flattrendz.com --all
```

When I clicked "y" for database drop, i got below error:

```
ERROR 2005 (HY000): Unknown MySQL server host '-u' (0)
[ Tue May  6 17:25:42 EDT 2014 ]  Unable To Drop  Database
```

The files were deleted. When I try to create a new site with the same domain, I see "Already Exists" error.

**Comment by Harry-Harrison** [comment]
Is this fixed? I'm having this issue right now.
