### ISSUE TITLE
MySQL root password

### ISSUE THREAD

**Issue by thenoobi** [rtCamp/easyengine#241]
Where to find mysql root password and change it?

**Comment by nyala1** [comment]
Thanks loads. Saved me!

**Comment by kcpt-steven-kohlmeyer** [comment]
Where is the .my.cnf file located?  Has this changed in a newer version?

**Comment by iam404** [comment]
From EE v3.3.5 , location for my.cnf has been set to 

`/etc/mysql/conf.d/my.cnf`

**Comment by kcpt-steven-kohlmeyer** [comment]
Awesome thanks!

**Comment by animeshsinghweb** [comment]
@iam404 

Thanks mate,

I was searching for it in root, and was tired. I think mate, @rahul286  this info must also be updated in EasyEngine FAQs, as I was misconfused from there only.

**Comment by sagargulati** [comment]
After this, do we need to reboot or restart anything, since it's not taking changes to change the new root password and still working with old password.

**Comment by nguyenvanhieuvn** [comment]
Where my.cnf in EEv4?
