### ISSUE TITLE
Installation fail on Ubuntu 14.04 LTS (packages cannot be authenticated)

### ISSUE THREAD

**Issue by sebstam** [rtCamp/easyengine#245]
Following the installation guide, after 'ee system install' command unfortunately I get an error resulting in no successful installation.

Tried several times on two fresh DigitalOcean droplets running Ubuntu 14.04 LTS. Worked before. Will try on older Ubuntu now.

Any idea how to fix? Can we install easyengine somehow bypassing this authentication notice?

WARNING: The following packages cannot be authenticated!
  php5-common php5-curl php5-json php5-fpm php5-gd php5-imap php5-mcrypt
  php5-cli php5-readline php5-xmlrpc php5-mysqlnd php-pear php5-memcache
  php5-xdebug
E: There are problems and -y was used without --force-yes
[ Thu May 15 09:25:03 EDT 2014 ]  Unable To Install Nginx PHP5 MySQL Postfix 

Screenshot of terminal: http://cl.ly/image/2g1j0S3Q0A2f

Thanks in advance for your help, easyengine is an amazing tool for quick and easy Nginx playgrounds.

**Comment by dinhkk** [comment]
thanks @thenoobi 
it's great, it worked
