### ISSUE TITLE
Multisite sub blog to replace main blog

### ISSUE THREAD

**Issue by shaneholloman** [rtCamp/easyengine#254]
If a site is developed as a sub blog at;
subblog.mainnetwork.com is blog ID2
At:
mainnetwork.com is blog ID1 but now needs to be the new main blog. What it the method for this?

Another way to ask is how we make blog ID2 become the new network master blog?

A lot of searching hasn't revealed much information regarding this. I hope someone here has the method

*Maybe could a feature request for EE*

**Comment by rahul286** [comment]
I did this very long time ago manually by database modifications.

It had something to do with wp_site and wp_blogs tables - http://codex.wordpress.org/Database_Description#Multisite_Table_Overview

WordPress Multisite allows creation of multiple-multisite network in single install! Sounds crazy but it felt like inception. I created 3 networks and divided all sub-sites under three networks. All 3 sites were "primary" for sub-sites.

I guess I also used a plugin like - https://wordpress.org/plugins/wp-multi-network/

But I never liked WordPress multisite for anything complicated. That is one reason we started EasyEngine as we wanted to create many wordpress sites but easily.
