### ISSUE TITLE
Adding additional subdomains/domains after site configured?

### ISSUE THREAD

**Issue by dovy** [rtCamp/easyengine#261]
I am trying to map out a system. I am having ee install wordpress multi-site instances, using subdomains. What I know my users want to do, is have the ability to change the domain from xxx.MyDomain.com to either their own top level subdomain, or another subdomain.

My ideal configuration would let them enter the WordPress instance from either URL, and/or redirect to their secondary.

How would you suggest I go about making this happen? I'd prefer not to manually do this, but rather let it be dynamic.

Any ideas?

**Comment by rahul286** [comment]
@dovy I hope your issues is solved by now.

If not, please use free community support forum at - http://community.rtcamp.com/c/easyengine 

We are also offering premium support at https://rtcamp.com/products/easyengine-premium-support/

Please check more details at - https://github.com/rtCamp/easyengine/blob/master/CONTRIBUTING.md
