### ISSUE TITLE
EasySetup

### ISSUE THREAD

**Issue by JosefJezek** [rtCamp/easyengine#266]
I write script called EasySetup. Command-line setup tool with Markdown config files using WP-CLI.

https://github.com/OpenWP/EasySetup

Could you add link to your README? I can write module for final EE new version.

**Comment by rahul286** [comment]
@JosefJezek Is your script updated for new EE 3.x?

Also, have you checked new plugin architecture - http://docs.rtcamp.com/easyengine/dev/plugins/ ?

We are working on documentation but I hope with EE 3.x, you will be able to write modules easily.
