### ISSUE TITLE
Opcode Cache is 100% - How do I increase this correctly?

### ISSUE THREAD

**Issue by shaneholloman** [rtCamp/easyengine#274]
https://traffic.mg:22222/cache/opcache/opgui.php?page=overview

shows 100% usage:

```
total memory: 64.000MB
used memory: 44.552MB
free memory: 19.448MB
wasted memory: 0.000 bytes (0%)
number of cached files: 339
number of hits: 3
number of misses: 339
blacklist misses: 0
number of cached keys: 370
max cached keys: 3,907
```

**Comment by nautinz** [comment]
has this file`since move ```/etc/php5/fpm/conf.d/05-opcache.ini``` does not exist in my installation so I ran ```ee stack install --admin``` and didn't help

I need to increase opcache amount as it is full

**Comment by nautinz** [comment]
managed to ```nano /etc/php5/fpm/conf.d/05-opcache.ini``` 
added
```
opcache.memory_consumption=512
opcache.max_accelerated_files=50000
``` 

reload stack services and it increase my opcache - that's good - but
Still can't clean opcode cache via ```ee clean --all```


A clear step by step would be amazing
