### ISSUE TITLE
Won't install with Debian 7 64bit Minimal

### ISSUE THREAD

**Issue by codxse** [rtCamp/easyengine#292]
I can't install easy engine with this command `wget -qO ee rt.cx/ee && sudo bash ee` and `wget -qO ee rt.cx/ee && sudo bash ee`. Is there anything I missed?

**Comment by mehargags** [comment]
I tried the installation one-liner:
__wget -qO ee rt.cx/ee && sudo bash ee__
but that doesn't do anything at all - just downloads ee Script.
 
P.S. I tried it on fresh ubuntu 14.04 x64 and Debian 7 x64. Wget was already installed. 
Albeit I got it install the "curl" way.
Would be good if you fix this issue or shed some light on possible Causes and Remedies in a wiki

**Comment by solhuebner** [comment]
Same issue on 14.04.02 minimal
