### ISSUE TITLE
Finalizing my stack changing default websites directory to /home and disabling named

### ISSUE THREAD

**Issue by enricodeleo** [rtCamp/easyengine#338]
Hi everyone,

this is my first experience with easyengine and I have to say it is a great tool to bootstrap a wordpress webserver bstack!

BTW I've done a few modification in order to fit my own needs such as:
- installed fail2ban, maldet, rkhunter and clamav for security
- installed ssmtp in order to send system mails via smtp (I use my server only for the web application and I have DNS and Mail handled by external saas)
- swapped php-fpm in favor of HHVM with fastcgi (easy as I pie since it also uses port 9000 with fast_cgi mode)
- secured all ports but ssh and web ports via ufw

Now, I to complete my job I would stop named service since I don't use this server as DNS server. As far as you know, is it safe? Are there any issues doing such a thing?

Another important question is: can I change the default behavior of creating websites under /var/www and have those directories filed under /home ? The partition table my provider deploys allocates almost all the storage to /home, and I'm sure I'l run out of storage soon. Here is my partition table (don't understand the "none" filesystems):

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        20G   14G  4.3G  77% /
devtmpfs        2.0G  4.0K  2.0G   1% /dev
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            394M   39M  356M  10% /run
none            5.0M     0  5.0M   0% /run/lock
none            2.0G     0  2.0G   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/sda3       1.8T  5.3G  1.7T   1% /home
```

My OS is Ubuntu 14.04.1 LTS and EE version is 2.2.1

Thank you in advance!

**Comment by greenyang** [comment]
+1... I made a partition disk and mounted with fstab setting, but EasyEngine is still unable to be install to custom partition disk location :frowning: Keep expecting~
So @enricodeleo , did you get a solution to achieve that?  How did you do that?
I want keep independent mounted partition disk (like /sda for boot,ee, and /sdb for all wordpress website contents including DB) on my VPS...
