### ISSUE TITLE
AWS static IP

### ISSUE THREAD

**Issue by QROkes** [rtCamp/easyengine#343]
When you are using AWS as a hosting provider and have an static IP for your server could be a headache each time you restart the server, so here is the code to ensure your server is getting the static IP each time.

It could be nice if you add it as a templeate in EE in the case somebody needs to use it.

//TURN ON MULTIVERSE  
sudo nano /etc/apt/sources.list

//UPLOAD AWS CREDENCIALS .PEM TO OPT FOLDER  
sudo chown -R ubuntu:www-data /var/opt
sudo mkdir /var/opt/ec2
sudo chown -R root:root /var/opt

sudo apt-add-repository ppa:awstools-dev/awstools
sudo apt-get update
sudo apt-get install ec2-api-tools

//UPDATE rc.local 
sudo nano /etc/rc.local

export EC2_KEYPAIR=<NAME> # name only, not the file name
export EC2_URL=https://ec2.us-east-1.amazonaws.com
export EC2_PRIVATE_KEY=/var/opt/pk-private key file>.pem
export EC2_CERT=/var/opt/cert-file.pem
export JAVA_HOME=/usr/lib/jvm/java-6-openjdk/

// AWS Creds:
export AWS_ACCESS_KEY=<aws access key>
export AWS_SECRET_KEY=<aws secret key>

// get EC2 instance ID
instanceid=`/usr/bin/curl -s http://169.254.169.254/latest/meta-data/instance-id` 

//Associate EIP with the captured instance ID.
ec2-associate-address -i $instanceid YOUR STATIC IP

**Comment by rahul286** [comment]
@QROkes what about Amazon's elastic IP?

Installing JAVA for above seems overkill.

Also why not use http://httpbin.org/ip to get public IP of server (unless you are running behind load balancer)
