### ISSUE TITLE
Upgrade-safe custom nginx config 

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#352]
Just come across http://community.rtcamp.com/t/woocommerce-and-easyengine/3201/6

Its very common to have some custom nginx config. 

We need a better way to handle it.

### Proposal

1. All custom nginx config should go under `/var/www/example.com/nginx/` (a new folder outside `htdocs`)
2. Under `nginx` we can have multiple files ending in `.conf` extension. All of them will be loaded inside `/etc/nginx/sites-available/example.com` towards end with something like `include /var/www/example.com/nginx/*.conf`
3. [optional] A user may want to fully override original (automated config). In that case, he may be able to update/create site with `--custom-config` flag. This new command can move all config to `/var/www/example.com/nginx/` and change original file to `/etc/nginx/sites-available/example.com` only to have only one line `include /var/www/example.com/nginx/*.conf`. This step is needed so easyengine can support such 100% custom config during future updates.

Need to decide

- [ ]  `/var/www/example.com/conf/nginx` or  `/var/www/example.com/nginx`

I think `/var/www/example.com/conf/nginx` will be better for php and other configs

**Comment by rahul286** [comment]
Added in 3.1.0

All configs will be in `/var/www/example.com/conf/nginx`

So if user want to add anything, they can use create their own `.conf` file in `/var/www/example.com/conf/nginx/`

**Comment by vercotux** [comment]
This is not working for me. I tried putting config files in both `/var/www/<site>/conf/nginx` and `/var/www/<site>/conf` but they are being ignored entirely. Do I need to do anything else to make it work? Where is this documented?
