### ISSUE TITLE
Modify ee to not disqualify Raspbian

### ISSUE THREAD

**Issue by rippler** [rtCamp/easyengine#356]
I know there may be other issues, but at least the OS shouldn't be disqualified considering it's a Debian.
```
user@raspberrypi:~$ cat /etc/debian_version
jessie/sid
```

**Comment by rahul286** [comment]
@rippler as this is very old issue, I am closing this for now. 

I moved this to idea tracker - https://rtcamp.com/idea/raspbian-support/

**Comment by RavanH** [comment]
Old issue but it seems to be possible with a small work-around http://community.rtcamp.com/t/easyengine-on-a-raspberry-pi/2603/2 ... can anyone confirm?
