### ISSUE TITLE
[Poll] Percona v/s MariaDB

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#362]
Update (25 Dec 2014)
====

@rtCamp/easyengine Lets do this in a slight different way.

## Fresh Setup
- [x] Modify install script so it installs MariaDB instead of Percona

## Existing Servers
- [x] Create a new command `ee stack migrate`. Then add option `--mariadb`. 
- [x] When `ee stack migrate --mariadb` is run, first throw error if remote mysql is used. Exit if, mariadb already installed. Then display a message like below:
> If your database size is big, migration may take some time. 
> During migration non nginx-cached parts of your site may remain down
> Type "mariadb" to continue? ___

If user types `mariadb` then only script will proceed. This will prevent accidental enter, y, yes type of answers.

Update (16 Dec 2014)
======

MariaDB is finalized. We are leaving poll open for more suggestions and feedback.

- [x] Check if Performance Schema is OFF by default in MariaDB. -  https://github.com/rtCamp/easyengine/issues/326
- [x] Percona to MariaDB upgrade script. I think Percona can handle this

------

We started with MySQL.

We switched to Percona sometime back.

Some users like MariaDB more. 

We did not use MariaDB because one we migrate to MairaDB 10, I think there is no way to go back to MySQL or Percona.

But Percona has issues and there are bugs which affected us recently. Like - https://bugs.launchpad.net/percona-server/+bug/1390695

So we just wish to how EasyEngine users compare Percona v/s MariaDB?

**Comment by rahul286** [comment]
@rtCamp/easyengine Lets do this in a slight different way.

## Fresh Setup
- [ ] Modify install script so it installs MariaDB instead of Percona

## Existing Servers
- [ ] Create a new command `ee stack migrate`. Then add option `--mariadb`. 
- [ ] When `ee stack migrate --mariadb` is run, first throw error if remote mysql is used. Then display a message like below:
> If your database size is big, migration may take some time. 
> During migration non nginx-cached parts of your site may remain down
> Type "mariadb" to continue? ___

If user types `mariadb` then only script will proceed. This will prevent accidental enter, y, yes type of answers.

**Comment by gau1991** [comment]
EasyEngine 3.0.5 release with MariaDB support
