### ISSUE TITLE
Sanity Checks for Multi-Server Setups (on *all* packages)

### ISSUE THREAD

**Issue by iouxui** [rtCamp/easyengine#381]
In the process of setting up a small cluster, one w/ NGINX, PHP, and WP-CLI, the other with MySQL (all handled individually through `ee` using `ee stack install [insert call]`), 

Steps to Reproduce:

1). `wget -qO ee rt.cx/ee && sudo bash ee`
2). `ee stack install nginx php wpcli` (on the `web` server)

1). `wget -qO ee rt.cx/ee && sudo bash ee`
2). `ee stack install mysql` (on the `myqsl` server)

Both clean installations, nothing on either prior. MySQL was setup and configured after installation to listen in on its private IP (valid and working), though when I ran

`ee site create domain.com --wpsubdom --wpfc`

The installer proceeded to install MySQL, Postfix, Admin Tools, etc. Basically as if nothing had been installed prior, or a check was not performed / skipped.

Last I recall, all that's needed for php5-fpm is the php5-mysqlnd package?

That said, since it proceeded to install MySQL, it wiped the configuration and failed to connect to the actual MySQL server as a result.

**Comment by rahul286** [comment]
@iouxui I am closing this issue as this is very old.

If you face any issue again, please use free community support - http://community.rtcamp.com/c/easyengine 

We are also offering premium support at https://rtcamp.com/products/easyengine-premium-support/

Please check more details at - https://github.com/rtCamp/easyengine/blob/master/CONTRIBUTING.md
