### ISSUE TITLE
XML Sitemap from All in One Seo Pack not working - Redirection issue

### ISSUE THREAD

**Issue by felixcoolb** [rtCamp/easyengine#387]
My blog is http://www.99blogger.com/
So my sitemap file must be in http://www.99blogger.com/sitemap.xml
But http://www.99blogger.com/sitemap.xml redirect to http://www.99blogger.com/sitemap_index.xml
And shows this page
![screenshot_8](https://cloud.githubusercontent.com/assets/10450108/5663445/edd3eae6-976c-11e4-8919-ab9e5c28d0d9.jpg)

I removed the yoast configuration lines in wpcommon.conf still no use
This is my current wpcommon.conf
<-----Start----->
# WordPress COMMON SETTINGS
# DO NOT MODIFY, ALL CHNAGES LOST AFTER UPDATE EasyEngine (ee)

# Limit access to avoid brute force attack
location = /wp-login.php {
	limit_req zone=one burst=1 nodelay;
	include fastcgi_params;
	fastcgi_pass php;
}

# Disable wp-config.txt
location = /wp-config.txt {
	deny  all;
	access_log off;
	log_not_found off;
}

# Disallow php in upload folder
location /wp-content/uploads/ {
	location ~ \.php$ {
		#Prevent Direct Access Of PHP Files From Web Browsers
		deny all;
	}
}
<-----End----->

Help me solve this issue

**Comment by rahul286** [comment]
@felixcoolb I see you have shifted to yoast SEO plugin - http://www.99blogger.com/sitemap_index.xml so I am closing this issue.

For future technical support, please use free community support - http://community.rtcamp.com/c/easyengine 

We are also offering premium support at https://rtcamp.com/products/easyengine-premium-support/

Please check more details at - https://github.com/rtCamp/easyengine/blob/master/CONTRIBUTING.md
