### ISSUE TITLE
proxy site type

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#389]
Nginx is used as front-end proxy in many different systems.

So it might be convenient to have something like

```
ee site create example.com --proxy=host[:port] 
```

`--proxy-host hostname` may be needed in some case when we decide to send different hostname than `example.com`

`--cache` could be other parameter to turn on/off proxy cache.

We may implement this before https://github.com/rtCamp/easyengine/issues/319 and then use `ee site crete X --proxy` command internally for `ee site create X --ghost`

**Comment by harshadyeola** [comment]
nice idea :+1:

**Comment by gau1991** [comment]
+1

**Comment by gau1991** [comment]
Added Proxy site type in EasyEngine 3.1.2
