### ISSUE TITLE
ee debug --mysql

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#390]
> ERROR 1227 (42000) at line 1: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
[ Wed Jan 14 10:24:34 UTC 2015 ] Unable to setup slow_query_log, exit status =  1

Amazon RDS in use. 

We need to handle errors for remote mysql scenario.

**Comment by gau1991** [comment]
Handled all remote MySQL is service and debug with EasyEngine 3.0.3
