### ISSUE TITLE
Unable to download WordPress, exit status =  255

### ISSUE THREAD

**Issue by AsaadQ** [rtCamp/easyengine#392]
This is fairly unknown VPS provider and a new error i am experiencing, when i run

 ee site create www.mysite.biz --wpfc

i get:

Creating mysite.biz, please wait...
Creating symbolic link for mysite.biz
Creating htdocs & logs directory
Downloading WordPress, please wait...
[ Thu Jan 15 01:01:16 AST 2015 ] Unable to download WordPress, exit status =  255

**Comment by frederichoule** [comment]
Same problem here.

**Comment by frederichoule** [comment]
@rahul286 any idea what's causing this error?

**Comment by gau1991** [comment]
@frederichoule ,
Can you give us last few lines from easyengine log file?
location is `/var/log/easyengine/ee.log`

**Comment by frederichoule** [comment]
I will - in a few minutes. I just deleted the entire server and started from scratch.

**Comment by frederichoule** [comment]
It installed correctly this time. Sorry about that.

**Comment by gau1991** [comment]
@frederichoule ,
First time might be network issue, 
we will keep this issue open for few more days, lets observe any one else face this issue

**Comment by frederichoule** [comment]
If it was a network issue, what would have been the way to continue after that? I tried to delete the site, and it gave "Error database doesn't exist, exit code something".

**Comment by gau1991** [comment]
@frederichoule ,
As db was missing, to delete files you can use
```
ee site delete kaushal.tuxcron.com --files
```

**Comment by frederichoule** [comment]
Thank you.

**Comment by gau1991** [comment]
I am closing this issue, as no other one is facing this, Feel free to re open if you face again.
