### ISSUE TITLE
Percona MySQL does not install on Ubuntu 14.04 LTS 

### ISSUE THREAD

**Issue by jeffreynolte** [rtCamp/easyengine#395]
I get the following error when trying to install EE.  In addition I have attempted to debug with the issue #321 and I am receiving the same error:
```bash
Installing Percona MySQL, please Wait...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package percona-server-server-5.6
E: Couldn't find any package by regex 'percona-server-server-5.6'
[ Mon Jan 26 14:18:48 EST 2015 ] Unable to install Percona MySQL, exit status =  100
```

**Comment by rippler** [comment]
I installed EE on U14.04 five mins ago, but I previously manually (`apt-get install`) installed `mysql-server-5.6` and other packages, and it installed fine. But if you want to run the Percona edition, this won't help you (maybe you can add the repo and manually install it? http://www.percona.com/doc/percona-server/5.6/installation/apt_repo.html)

**Comment by gau1991** [comment]
@jeffreynolte ,
Look like your distro dont have Package for Percona.
Can you give me output of following command?

```
lsb_release -a
ee version
ls /etc/apt/sources.list.d/
```

**Comment by jeffreynolte** [comment]
@gau1991 - thanks for taking a look. see below.
```bash
EasyEngine (ee) version: 2.2.2
ondrej-php5-trusty.list  rtcamp-nginx-trusty.list
percona-trusty.list	 rtcamp-nginx-trusty.list.save
```

**Comment by QROkes** [comment]
Seems that is impossible to use EE for new/fresh installations right now, it seems to be a percona issue, I can't even install percona manually.
(AWS-Ubuntu 14.04-EC2 instance)

**Comment by rippler** [comment]
If you can't install it manually, isn't that a Percona bug?

**Comment by gau1991** [comment]
Hello we fixed this issue to EE 2.2.3,
I am closing this issue now.

**Comment by QROkes** [comment]
It's not working out for me.
I fixed it adding the port to the url:
src/modules/stack/install/ee_mod_repo_mysql.sh
gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 1C4CBDCDCD2EFD2A

http://askubuntu.com/questions/134913/cant-add-repo-keys

**Comment by gau1991** [comment]
@QROkes ,
Which version of Ubuntu you are using?
We tested the stable, we have not faced any sort of issue on it.

**Comment by QROkes** [comment]
AWS-Ubuntu 14.04-EC2 instance

**Comment by MattyLB** [comment]
@Cristhian - I've been using an AWS-based AMI of *Ubuntu 14.04.1 LTS* on
EC2 with Easy Engine 2.2.2, Percona, Nginx + HHVM for several months now
without issues in regards to Percona.  So if you're using a different
Ubuntu 14.04 AMI, you may want to switch to the 14.04.1 LTS version
provided when you create a new instance in AWS.

@rtCamp - here is my working configuration to verify. Is there a command I
can use to check my Percona version directly? ...

ls /etc/apt/sources.list.d/
hhvm.list                ondrej-php5-trusty.list.save
percona-trusty.list.save  rtcamp-nginx-trusty.list.save
ondrej-php5-trusty.list  percona-trusty.list
rtcamp-nginx-trusty.list

EasyEngine (ee) version: 2.2.2

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
--------------------------------------
Hope this helps
