### ISSUE TITLE
http://httpbin.org/ - useful service

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#398]
We can make use of for few things http://httpbin.org/

e.g. http://eu.httpbin.org/ip

**Comment by MiteshShah** [comment]
@rahul286 That service only works if user not used any VPN, Proxy or Tor.

Now a days some of hosting provider only allow to access server using VPN in that case use have to configure VPN and above service return VPN or Proxy ip address.

**Comment by rahul286** [comment]
I am aware of VPN issues but those who are using VPN must be advanced/enterprise user.

In real-life cases, I haven't come across a EE server running behind VPN. 

We can show IP detected and ask user to press "Y" to accept it OR change it by giving real-ip.

**Comment by MiteshShah** [comment]
> We can show IP detected and ask user to press "Y" to accept it OR change it by giving real-ip.

:+1:

**Comment by gau1991** [comment]
Duplicate of https://github.com/rtCamp/easyengine/issues/358
