### ISSUE TITLE
Installing with mysql db hosted on another server

### ISSUE THREAD

**Issue by geophray** [rtCamp/easyengine#401]
I've tried following the directions [here](https://github.com/rtCamp/easyengine/wiki/FAQ#how-to-change-mysql-host-from-localhost-to-another-host) to install wordpress with the mysql host set to be something other than localhost, but no matter what I do, the databases still get set up on localhost.

Here is what is in my ee.conf file:

[mysql]
        grant-grant-host = localhost
        db-name = true
        db-user = true
        grant-host = localhost
        mysqlhost = mycustomhost

I'm not sure where the disconnect is.  It's likely user error...

**Comment by geophray** [comment]
Upon doing a little more digging, I found [this](https://rtcamp.com/easyengine/docs/remote-mysql/), which gave me the missing pieces.

**Comment by geophray** [comment]
Upon site creation, I'm getting the following error now:

"Unable to create WordPress tables for example.com, exit status =  1"

I'm running Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-45-generic x86_64) and EasyEngine 2.2.3.

I'm using the following command:  sudo ee site create example.com --wpfc

**Comment by geophray** [comment]
I failed to mention that I am hosting mysql on an AWS RDS instance.  The database is being created, so I know the username and password are accurate, but it fails to create the database tables.

**Comment by gau1991** [comment]
@geophray ,
Hi.
Make sure your `~/.my.cnf` looks like following
```
[client]
host=<RDS_HOST>
user=<RDS_USER>
password=<RDS_PASSWORD>
```

And MySQL section in EasyEngine configuration looks like following
```
[mysql]
	grant-host = %
	db-name = false
	db-user = false
```
I hope this will help you.

**Comment by geophray** [comment]
Thanks @gau1991!  That did the trick.  There was another value in the [mysql] section (grant-grant-host) but I removed it since it wasn't in yours.  Is there any need for it?

**Comment by gau1991** [comment]
Nope, its not needed..
