### ISSUE TITLE
InfiniteWP - "Control ALL your sites from a single, powerful admin panel."

### ISSUE THREAD

**Issue by karlhaworth** [rtCamp/easyengine#402]
Would it be helpful to incorporate something like [InfiniteWP](http://infinitewp.com)? I use it so I can easily manage (update mainly) my plugins across all the sites. It also offers backup functionality.

I was hesitant to post this, because most of these useful features will be built into EE or are already in WP-CLI. Backup support is being created for EE. Plugins can be done through WP-CLI. I just think it's helpful to be able to control all sites at once. Occasionally I'll even install plugins across the board like BruteForce or Clef.

**Comment by rahul286** [comment]
Can you please provide some details as how do you want EasyEngine to work with InfiniteWP?

The goal is to make our lives "Easier". Anything that meets this goal is welcome. Feel free to post your ideas and suggestions. :-)

**Comment by karlhaworth** [comment]
Most people using EasyEngine have multiple WordPress installs. This gives you the ability to update all plugins and wordpress versions from one interface. That's what's easier. You don't have to log into each website to complete this task.

**Comment by matthewkeath** [comment]
Yes, but how would you incorporate it? 

They are kinda separate things.

**Comment by rahul286** [comment]
I never used InfiniteWP but tried ManageWP sometime back. I guess they are similar.

I think a user of InfiniteWP or ManageWP would expect some WordPress plugin to be installed and configured by EasyEngine, each time a WordPress site is created using `ee site create --wp` command.
Not sure if the process can be fully automated or will require some unique input e.g. unique-key per site or some other step.

From EasyEngine perspective, this is possible using EE plugin - http://docs.rtcamp.com/easyengine/dev/plugins/

**Comment by joeguilmette** [comment]
This sounds a little heavy. I think easy engine can live just fine without
this, and installing infinite wp on your own is quite easy.

There was also just recently a huge security issue with infinite wp.

**Comment by rahul286** [comment]
@joeguilmette EasyEngine will not have it in core. I was suggesting that such things can be developed using EasyEngine plugin system.

**Comment by joeguilmette** [comment]
Ah ok! That's awesome.
