### ISSUE TITLE
Tutorials vs ee

### ISSUE THREAD

**Issue by frederichoule** [rtCamp/easyengine#403]
Hello!

In the tutorials, you write: "If you are using easyengine, you can accomplish everything in this article using command". https://rtcamp.com/wordpress-nginx/tutorials/single-site/fastcgi-cache-with-purging/

But, in the tutorial, you say to enable "Enable Cache Purge". When I check on my EE Installed WP, it's not enabled. Should I do it? Or you do it from another way?

Thanks.

**Comment by gau1991** [comment]
Right now EasyEngine is now doing that settings, you have to do that manually.

**Comment by frederichoule** [comment]
And do I have anything to do in the W3 Total Cache plugin, or it's all setup? I'm trying to do the FastCGI Cache.

**Comment by gau1991** [comment]
Actully EasyEngine tells you what setting you should do at the end of site creation:
```
Configure nginx-helper:	http://example.com/wp-admin/options-general.php?page=nginx
Configure W3TC:		http://example.com/wp-admin/admin.php?page=w3tc_general
Page Cache:		Disable
Database Cache:		Memcached
Object Cache:		Memcached
Browser Cache:		Disable
```

**Comment by frederichoule** [comment]
You are right. Sorry.
