### ISSUE TITLE
Initial load delay

### ISSUE THREAD

**Issue by frederichoule** [rtCamp/easyengine#405]
I have a Wordpress that I run on 2 different domains.

First one is running on NGINX, with WP Super Cache, and the second one is running on a EE installation of NGINX with FastCGI Cache.

The first one has no delay at all when loading the page, while the EE-configured one, with FastCGI Cache, has a 0.3 delay that is very very perceptible to the user.

Also, killing PHP makes the website unavailable, while I thought the "fastcgi_cache_use_stale" was supposed to serve a cached copy of the page?

Any way to find what's causing this and fix these errors?

**Comment by rahul286** [comment]
> Also, killing PHP makes the website unavailable, while I thought the "fastcgi_cache_use_stale" was supposed to serve a cached copy of the page?

Page will be served from cache only if its cached before PHP was killed.

To test:

1. Start PHP
2. Open Page (so it gets cached)
3. Stop PHP
4. Open page again. At this point if cache is working properly, you will get page from cache even if PHP is down.

** `fastcgi_cache_use_stale` is slightly different. **

Check following scenario:

1. Nginx check if requested page is cached.
2. If cached, check if cache is "still" fresh. Refers to `inactive` value from line like `fastcgi_cache_path ... inactive=60m;`
3. If fresh, server from cache
4. If not fresh, i.e. if stale, request fresh copy from backend PHP
5. At this point, if backend PHP is available, fresh copy of page will be returned by PHP to Nginx. Nginx will return this copy to visitor and update fastcgi-cache for subsequent requests.
5. But, if backend PHP is **not** available, `fastcgi_cache_use_stale` is checked. 
6. If backend is down **and** `fastcgi_cache_use_stale` is **false**, 500 HTTP server error will be returned.
6. If backend is down **but** `fastcgi_cache_use_stale` is **true**, page will be returned from cache.

I hope above clears your doubt.

**Comment by frederichoule** [comment]
Hello,

I tried exactly what you describe on a brand new WP created using "ee site create domain.com --wpfc", and yet, when I "service php5-fpm stop", I get a Bad Gateway error from NGINX.

**Comment by rahul286** [comment]
Do you have any wordpress plugin installed?

Some plugins can prevent caching of wordpress pages.

**Comment by rahul286** [comment]
By the way apart from PHP start/stop, with `--wpfc` you can simply run `curl -I domain.com`.

You should see HIT there. You may send you site URL here, so I can have a look at it.

**Comment by fourleafed** [comment]
@frederichoule Are you sure you are logged out of your website after you have stopped PHP? You might also want to check whether 'disable cache for loggedin users' is disabled.
