### ISSUE TITLE
Easy Engine Stack - unrecognized arguments

### ISSUE THREAD

**Issue by respondiv** [rtCamp/easyengine#408]
Hello,

I just installed a fresh copy of easyengine on my test server at DO. When I use "ee stack install" command it ony installed Nginx, PHP, MySQL, Postfix and WP-CLI.

I tried to use "ee stack install phpMyAdmin" command and it gives following error

usage: ee (sub-commands ...) [options ...] {arguments ...}
ee: error: unrecognized arguments: phpMyAdmin

When I tried "ee stack install admin", it gives same error

usage: ee (sub-commands ...) [options ...] {arguments ...}
ee: error: unrecognized arguments: admin

Was this intended and all the admin tools were removed? If not, how can I fix it ?

BTW, I appreciate your job on EasyEngine.

Thanks.

**Comment by rahul286** [comment]
Can you try `ee stack install --all` to install everything?

Syntax is changed bit after today's release.

Doc - http://docs.rtcamp.com/easyengine/commands/stack

**Comment by respondiv** [comment]
Awesome ! Thank you :)

**Comment by hmaesta** [comment]
Should update here: https://easyengine.io/tutorials/linux/ubuntu-php-mysql-nginx-postfix/

`ee system install all`
