### ISSUE TITLE
Can't install ee stack on fresh machine: "No package named 'nginx-custom'"

### ISSUE THREAD

**Issue by vitaligent** [rtCamp/easyengine#409]
Here's the stack trace. I'm happy to provide more details or let you login to my machine. Thanks for creating easyengine. I love this project!

root@quad:~# ee stack install
Adding repository for MySQL
Adding repository for Nginx
Adding repository for PHP
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 198, in __getitem__
    return self._weakref[key]
  File "/usr/lib/python3.4/weakref.py", line 125, in __getitem__
    o = self.data[key]()
KeyError: 'nginx-custom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ee", line 9, in <module>
    load_entry_point('ee==3.0', 'console_scripts', 'ee')()
  File "/usr/local/lib/python3.4/dist-packages/ee-3.0-py3.4.egg/ee/cli/main.py", line 84, in main
    app.run()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.4/dist-packages/ee-3.0-py3.4.egg/ee/cli/plugins/stack.py", line 1257, in install
    EEAptGet.install(self, apt_packages)
  File "/usr/local/lib/python3.4/dist-packages/ee-3.0-py3.4.egg/ee/core/aptget.py", line 86, in install
    if not install_package(self, package):
  File "/usr/local/lib/python3.4/dist-packages/ee-3.0-py3.4.egg/ee/core/aptget.py", line 64, in install_package
    pkg = apt_cache[package_name.strip()]
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 205, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'nginx-custom'"

**Comment by vitaligent** [comment]
I figured it out. The script needs to install "software-properties-common". It assumes it's there. So the add-apt-repository command fails.

**Comment by vitaligent** [comment]
The script also needs to install the "bsdutils" package. I'm installing this on a minimal config, so all these packages are probably assumed to be present.

Reopening issue because I didn't fix it myself in the source code. I can't seem to find where the list of packages is kept.

**Comment by kudabesix** [comment]
my own solution so far, installing software-properties-common and python-software-properties, then set locale to UTF-8 with this code:
`sudo locale-gen en_US.UTF-8`
`export LANG=en_US.UTF-8`

at least, in my server could work

**Comment by vitaligent** [comment]
@kudabesix - You are correct. I had to fix locale and install python-software-properties as well. Thanks.

**Comment by gau1991** [comment]
@kudabesix @vitaligent ,
Thanks for pointing this issue.
We all did all testing where our environment is en_US-UTF-8, so we never faced this issue.
We will fixing this issue as soon as possible in EE 3.0

**Comment by gau1991** [comment]
@kudabesix ,
What was your previous locale?
Can you give me output of following command?
```
echo $LANG
```

**Comment by xreeckz** [comment]
In my case I had to install "python-software-properties" to fix it.

**Comment by ddelaey** [comment]
Still not okay, here is what I did:

apt-get update && apt-get upgrade && apt-get dist-upgrade
apt-get install software-properties-common
apt-get install python-software-properties
echo $LANG
sudo locale-gen en_US.UTF-8
export LANG=en_US.UTF-8
apt-get install gcc
wget -qO ee rt.cx/ee && sudo bash ee
ee stack install --all

I'm getting this:

root@vm1855:~# ee stack install --all
System RAM is less than 1GB
Mail scanner packages are not going to install automatically
Adding repository for MySQL
Adding repository for Nginx
Adding repository for PHP
E:Unable to correct problems, you have held broken packages.

What else can be wrong?

**Comment by ddelaey** [comment]
root@vm1855:~# ee stack install --web
Gives this:
...
Downloading WP-CLI               [Done]
Reload : postfix   [OK]
Reload : nginx     [OK]
'ascii' codec can't decode byte 0xc2 in position 688: ordinal not in range(128)

root@vm1855:~# ee site create mysite.com --wpfc
Seems to install correctly, but I'm getting the following error in the browser:
502 Bad Gateway
nginx

The WP install did work fine with a EE2.2.3

What else can be wrong?
Thanks,
  David

**Comment by ddelaey** [comment]
Got it working :-)

By using the 'locale' command I could see the locale was not fully correct yet.
I needed to do:
export LC_CTYPE=en_US.UTF-8
sudo locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales (selecting first all and then en_US.UTF-8)

After that:
apt-get install software-properties-common
apt-get install python-software-properties
wget -qO ee rt.cx/ee && sudo bash ee
ee site create mydomain.com --wpfc

No more errors and site working fine :-)

Then I tried:
ee stack install --all

Now also the mail package is installed and working :-)

Note that on a local VM I also need to do 'apt-get install gcc'

When would the EE3.0 patch release come out?
Once the installation will be more robust this will be a great fast way to install the stack and WP :-) Thanks!

**Comment by ddelaey** [comment]
What's not working is:
https://webmail.mysite.com is not existing it seems.
The IMAP and POP access also don't seem to work.
What can be wrong here?

**Comment by hasinhayder** [comment]
Any idea when this issue will be addressed? Because it's literally broken at this moment :(

**Comment by gau1991** [comment]
@hasinhayder ,
We allready fixed this issue with EE 3.0.2,
Which version of EasyEngine you are using?
