### ISSUE TITLE
EE3.0.1 locale issue + mail issue, based on ticket #409

### ISSUE THREAD

**Issue by ddelaey** [rtCamp/easyengine#414]
Still not okay, here is what I did:

apt-get update && apt-get upgrade && apt-get dist-upgrade
apt-get install software-properties-common
apt-get install python-software-properties
echo $LANG
sudo locale-gen en_US.UTF-8
export LANG=en_US.UTF-8
apt-get install gcc
wget -qO ee rt.cx/ee && sudo bash ee
ee stack install --all

I'm getting this:

root@vm1855:~# ee stack install --all
System RAM is less than 1GB
Mail scanner packages are not going to install automatically
Adding repository for MySQL
Adding repository for Nginx
Adding repository for PHP
E:Unable to correct problems, you have held broken packages.

root@vm1855:~# ee stack install --web
Gives this:
...
Downloading WP-CLI [Done]
Reload : postfix [OK]
Reload : nginx [OK]
'ascii' codec can't decode byte 0xc2 in position 688: ordinal not in range(128)

root@vm1855:~# ee site create mysite.com --wpfc
Seems to install correctly, but I'm getting the following error in the browser:
502 Bad Gateway
nginx

The WP install did work fine with a EE2.2.3

What else can be wrong?

**Comment by ddelaey** [comment]
By using the 'locale' command I could see the locale was not fully correct yet.
I needed to do:
export LC_CTYPE=en_US.UTF-8
sudo locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales (selecting first all and then en_US.UTF-8)

After that:
apt-get install software-properties-common
apt-get install python-software-properties
wget -qO ee rt.cx/ee && sudo bash ee
ee site create mydomain.com --wpfc

No more errors and site working fine :-)

Then I tried:
ee stack install --all
to get the mail package installed too

What's not working is:
https://webmail.mysite.com is not existing it seems.
The IMAP and POP access also don't seem to work.
What can be wrong here?

Note that on a local VM I also need to do 'apt-get install gcc'

**Comment by harshadyeola** [comment]
@ddelaey 
Could you please give us details, Which distro you are using?

**Comment by ddelaey** [comment]
@harshadyeola 

root@vm1855:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy

root@vm1855:~# cat /proc/version
Linux version 3.2.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.2.60-1+deb7u1

Anything else you need to know?

Issues are:
- https://webmail.mysite.com does not exist
- IMAP and POP access do not seem to work
- After installing EE 'apt-get update' returns 'W: GPG error: http://repo.percona.com wheezy Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1C4CBDCDCD2EFD2A' at the end.

**Comment by gau1991** [comment]
@ddelaey ,
Thanks for responce,
I need some more details from you, so that we can debug more.
What is default locale?
```
locale
```
Also, if possible can you give me access to your server? so that I can debug more..
my public key is
````
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCfqNgxTMHWZSg+hDh3lsGPYQ9DH2mQo0zvrpyXtP5sBtk/w8pcJsPrB3LOTlVbhRVdHdR2thTHVtubSe3eg50UiCO7uXmnpU7OM0PX1JcYWWAw5dgDOxDxucHbPqJBKPtFH9Exf2+4+/h78m/Hg3XOfceYuzaYIaIkUhFG3/8/ah8+MXBvgc5IP7v7EKJIwfgFnWAec1wQBB/+G8+YAL8JR1QAtGkdAULo9lsI048M11/bQxWqTkDPHD6hCKhcseRZ5bV/IKeCZsB45GZrn2AtU2auQi2OSVBk/TOb/hlroPNj9m0BfliddlKiZms0qIxWgkMvorheOjLKXkDO5AB gaurav.astikar@rtcamp.com
```

**Comment by ddelaey** [comment]
@gau1991

root@vm1855:~# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

How exactly do I set up access for your public key? Never done that before. Thanks!

**Comment by gau1991** [comment]
```
vim /root/.ssh/authorized_keys
```
And you can paste their my keys

**Comment by ddelaey** [comment]
Added that.
IP = 185.53.169.64
Thanks!

**Comment by gau1991** [comment]
HI, I checked on your server, following are my points.

>  https://webmail.mysite.com does not exist

Webmail is working fine on your server.. There are two points, you have not added DNS record for webmail.example.com, and webmail listens on http not on https

> IMAP and POP access do not seem to work 

From log I checked that IMAP and POP is also working fine..
How you are accessing that? You can use your domain name i.e exmaple.com to access IMAP and POP. Also you can use port 143 for IMAP and 110 for POP

>  W: GPG error: http://repo.percona.com wheezy Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1C4CBDCDCD2EFD2A

I fixed this in your server. This is bug in EE 3.0.1, we will fix this today itself with EE 3.0.2

**Comment by ddelaey** [comment]
Thanks!

I used https for webmail because that is what is in the ViMbAdmin Administrator email I got for email account. Same for IMAP and POP, that email also stated SSL and ports 465 and 993/995.

Which exact records do I need to set to the webmail add to DNS? Is there a good pointer to documentation?

How can I have https for webmail too?

Currently I'm using a VPS at http://en.rootwelt.de
For another site I soon will use a VPS at http://transip.nl

**Comment by ddelaey** [comment]
This is a screenshot of the current DNS settings for the domain. I just modified mail to webmail some minutes ago.
![screen shot 2015-02-13 at 09 22 58](https://cloud.githubusercontent.com/assets/10964544/6184448/01753cc4-b362-11e4-87a6-aec6d124edfc.png)

**Comment by gau1991** [comment]
All local issue will be fixed with EE 3.0.3

**Comment by rahul286** [comment]
> ... will be ...

@gau1991 IMHO, issue should only be closed after fixing. Better with a commit message which actually fixes a particular issue

**Comment by michaelryanmcneill** [comment]
Is this currently fixed on master or on another branch? I can't deploy my boxes without fixing this local issue and since there is no commit message as referenced by @rahul286 I can't find a change.

**Comment by harshadyeola** [comment]
@michaelryanmcneill @ddelaey 
Checkout EasyEngine 3.0.3, all locale issues has been fixed in this release.
