### ISSUE TITLE
nginx connection reset by peer while reading from upstream

### ISSUE THREAD

**Issue by doringheorghe** [rtCamp/easyengine#416]
2015/02/13 20:04:29 [error] 31032#0: *12941 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 179.32.162.$
2015/02/13 20:04:29 [error] 31035#0: *12993 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 190.78.76.1$
2015/02/13 20:04:29 [error] 31031#0: *13080 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 190.62.22.4$
2015/02/13 20:04:29 [error] 31037#0: *10191 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 186.30.208.$
2015/02/13 20:04:29 [error] 31032#0: *12941 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 179.32.162.$
2015/02/13 20:04:29 [error] 31031#0: *13074 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 190.72.157.$
2015/02/13 20:04:29 [error] 31031#0: *13047 connect() failed (111: Connection refused) while connecting to upstream, client: 187.135.33.131, server: diose$
2015/02/13 20:04:30 [error] 31036#0: *13086 connect() failed (111: Connection refused) while connecting to upstream, client: 186.26.115.79, server: dioses$
2015/02/13 20:04:59 [error] 31041#0: *13365 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 181.59.177.$
2015/02/13 20:04:59 [error] 31034#0: *13389 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 187.195.240$

after i updated to 3.0.1

**Comment by gau1991** [comment]
@doringheorghe ,
Can you give me following information?
```
ee site info example.com
```
```
ee stack status
```

**Comment by doringheorghe** [comment]
It seems we have some errors. First If I want to create a new site with ee site create example.com --wpfc it gives me the following error:
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Downloading Wordpress 		[Done]
Setting up database		[Done]
Unable to move file from /var/www/example.com/htdocs/wp-config.php to /var/www/example.com

can I give you access to take a look ? one of my main production site's are using 3.0 and i feel its a lot buggy.
even PHP5-fpm wen't down last night..

**Comment by harshadyeola** [comment]
@doringheorghe 
Feel free to reopen issue if you are facing any issues
