### ISSUE TITLE
upgrade to EE3.0.2 returns a message that EE3.0.1 is already installed

### ISSUE THREAD

**Issue by ddelaey** [rtCamp/easyengine#420]
When trying to upgrade to EE3.0.2 I get a message I already have EE3.0.1

root@vm1855:~# wget -q http://rt.cx/ee && sudo bash ee
Executing apt-get update
You allready have EasyEngine 3.0.1

**Comment by ddelaey** [comment]
After doing 'ee stack install --admin' and ee stack install --mailscanner' it is fixed it seems.

Finished processing dependencies for ee==3.0.2
For EasyEngine (ee) auto completion, run the following command
source /etc/bash_completion.d/ee_auto.rc
EasyEngine (ee) installed successfully

**Comment by gau1991** [comment]
@ddelaey ,
You are getting this error because there is old `ee` update file in you system.
You can also use following command
```
wget -qO ee rt.cx/ee && sudo bash ee
```
Also we updated Readme with this command
