### ISSUE TITLE
Missing config file in EE 3.0.2?

### ISSUE THREAD

**Issue by Taikom** [rtCamp/easyengine#421]
I'm on a fresh Ubuntu 14.04LTS with the latest EE 3.0.2, but I can't seem to find the config file. It doesn't exist at /etc/easyengine/ee.conf

**Comment by respondiv** [comment]
Had the same issue, with the new version few commands format and locations were updated .. try  `/etc/ee/ee.conf`

**Comment by Taikom** [comment]
Thanks Respondiv, found it!
