### ISSUE TITLE
Not able to access PMA page

### ISSUE THREAD

**Issue by mattrin** [rtCamp/easyengine#422]
When I go to https://mysite.com:22222/db/pma it is giving an error that webpage is not available 
I have accessed it in the past. I have not changed any settings - what could be the error.

**Comment by mattrin** [comment]
Details on chrome show: Google Chrome could not load the webpage because mysite.com took too long to respond. The website may be down, or you may be experiencing issues with your Internet connection.

But I am able to access mysite.com without any issue.

Kindly advise...

**Comment by gau1991** [comment]
@mattrin ,
Have you installed PMA?
```
ee stack install --phpmyadmin
```
Also, it better if you check 22222 port error logs also
```
tail -f /var/www/22222/logs/*
```
