### ISSUE TITLE
Update to PHP 5.6

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#425]
```
sudo add-apt-repository ppa:ondrej/php5-5.6
sudo apt-get update
sudo apt-get upgrade
```

**Comment by MiteshShah** [comment]
DotDeb also provide php5.6 for debian 7.7

Refer: https://www.dotdeb.org/2015/02/02/php-5-6-5-for-wheezy/

**Comment by rahul286** [comment]
Great. :-)

I guess we can make a minor release to upgrade PHP and move to MariaDB. #362

**Comment by gau1991** [comment]
EasyEngine 3.1.2 released with PHP5.6
