### ISSUE TITLE
bug in `ee debug --stop` command

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#427]
```
> ee debug --stop
Nginx debug connection already disabled
PHP debug is allready disabled
PHP5-FPM log_level = debug  already disabled
Disabling MySQL slow log
Unable to execute statement
```

Last line `Unable to execute statement` seems to be because of memcache missing from this server. Please handle this condition.

Also notice typo in `PHP debug is allready disabled`

*allready* should be *already*

**Comment by gau1991** [comment]
Fixed with EasyEngine 3.0.3
