### ISSUE TITLE
Where is nginx.conf in ee 3?

### ISSUE THREAD

**Issue by AsaadQ** [rtCamp/easyengine#433]
i have to edit /etc/nginx/nginx.conf but the header 

	add_header X-Powered-By "EasyEngine 3.0.2";

is not located there, neither are any easyengine comments.

did it get moved?

**Comment by gau1991** [comment]
Hello @AsaadQ ,
In EE 3, We moved that to `/etc/nginx/conf.d/ee-nginx.conf` file
