### ISSUE TITLE
No prompt for admin tools during install

### ISSUE THREAD

**Issue by kjprince** [rtCamp/easyengine#436]
I ran the recommended install on a fresh node `wget -qO ee rt.cx/ee && sudo bash ee `

I never had an opportunity to set my username and password for admin tools. 

I installed them manually after a quick check in `/var/www/22222/htdocs` revealed no `db` directory.

I set my own admin + password combo and updated the port, also added my IP to `acl.conf` ....

I still can't seem to access the admin tools. 

I'm on ubuntu 14.04

**Comment by shitalp** [comment]
@kjprince ,
Hi, you need to run this ```ee stack install --admin``` then only you can able to access admin tools

**Comment by gau1991** [comment]
@kjprince ,
With EasyEngine 3.0.3 admin tools will be installed with default stack.
