### ISSUE TITLE
EasyEngine Global Variables

### ISSUE THREAD

**Issue by PoMkaNik** [rtCamp/easyengine#437]
Can't find file with EE global variables to follow article - https://rtcamp.com/tutorials/nginx/using-pagespeed/

No file on path from the article - /usr/local/lib/easyengine/lib/ee_lib_variables.sh
ee version 3.0.2

**Comment by gau1991** [comment]
@PoMkaNik , Thanks for pointing this..
That step is now not required with EE 3.0.2, also updated article
