### ISSUE TITLE
missing locations

### ISSUE THREAD

**Issue by lrkwz** [rtCamp/easyengine#438]
I've followed the standard super easy easy setup

    wget -qO ee rt.cx/ee && sudo bash ee

ended ok but ... when I execute

    ~# ee site create example-com --html
    Setting up NGINX configuration 	[Done]
    Setting up webroot 		[Done]
    Reload : nginx     [Failed]
    Unable to change owner : /var/www/example-com 

and

    ~# tail /var/log/nginx/error.log
    (...)
    2015/02/20 15:14:10 [emerg] 8913#0: open() "/etc/nginx/common/locations.conf" failed (2: No such file or directory) in /etc/nginx/sites-enabled/example-com:23

**Comment by gau1991** [comment]
Hi, You how you installed Nginx?
Also can you give me output of following command?

```
lsb_release -a
dpkg -l | grep nginx

```

**Comment by lrkwz** [comment]
~> lsb_release -a
    LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:cxx-3.0-amd64:cxx-3.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:cxx-4.0-amd64:cxx-4.0-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-3.1-amd64:desktop-3.1-noarch:desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:desktop-4.0-noarch:desktop-4.1-amd64:desktop-4.1-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch:graphics-4.1-amd64:graphics-4.1-noarch:languages-3.2-amd64:languages-3.2-noarch:languages-4.0-amd64:languages-4.0-noarch:languages-4.1-amd64:languages-4.1-noarch:multimedia-3.2-amd64:multimedia-3.2-noarch:multimedia-4.0-amd64:multimedia-4.0-noarch:multimedia-4.1-amd64:multimedia-4.1-noarch:printing-3.2-amd64:printing-3.2-noarch:printing-4.0-amd64:printing-4.0-noarch:printing-4.1-amd64:printing-4.1-noarch:qt4-3.1-amd64:qt4-3.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
    Distributor ID:	Ubuntu
    Description:	Ubuntu 14.04.1 LTS
    Release:	14.04
    Codename:	trusty
    ~> dpkg -l | grep nginx
    ii  nginx                                                       1.4.6-1ubuntu3.1                                    all          small, powerful, scalable web/proxy server
    ii  nginx-common                                                1.4.6-1ubuntu3.1                                    all          small, powerful, scalable web/proxy server - common files
    ii  nginx-core                                                  1.4.6-1ubuntu3.1                                    amd64        nginx web/proxy server (core version)

**Comment by gau1991** [comment]
@lrkwz ,
You have not installed Nginx with EasyEngine,
EasyEngine installs lastalls latest version Nginx 1.6.2
Purge your old Nginx and install with EasyEngine using ```ee stack install --nginx```

**Comment by lrkwz** [comment]
I think I hat a quite _wild_ situation:

```
~> sudo apt-get remove --purge nginx
[sudo] password for lrkwz: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  nginx*
0 upgraded, 0 newly installed, 1 to remove and 22 not upgraded.
After this operation, 95.2 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 556947 files and directories currently installed.)
Removing nginx (1.4.6-1ubuntu3.1) ...
~> sudo ee stack install --nginx
Nginx already installed
~> sudo ee stack status
php5-fpm  :  Running
mysql     :  Running
~> sudo ee stack start --nginx
Start : nginx     [OK]
~> sudo ee stack status       
php5-fpm  :  Running
mysql     :  Running
```

which has been resolved issuing also:

    sudo apt-get remove --purge nginx-common nginx-core

then

```
~> sudo ee stack install --nginx
Adding repository for Nginx
Selecting previously unselected package libluajit-5.1-common.
(Reading database ... 557247 files and directories currently installed.)
Preparing to unpack .../libluajit-5.1-common_2.0.2+dfsg-1_all.deb ...
Unpacking libluajit-5.1-common (2.0.2+dfsg-1) ...
Selecting previously unselected package libluajit-5.1-2:amd64.
Preparing to unpack .../libluajit-5.1-2_2.0.2+dfsg-1_amd64.deb ...
Unpacking libluajit-5.1-2:amd64 (2.0.2+dfsg-1) ...
Selecting previously unselected package nginx-common.
Preparing to unpack .../nginx-common_1.6.2-2ppa~trusty_all.deb ...
Unpacking nginx-common (1.6.2-2ppa~trusty) ...
Selecting previously unselected package nginx-custom.
Preparing to unpack .../nginx-custom_1.6.2-2ppa~trusty_amd64.deb ...
Unpacking nginx-custom (1.6.2-2ppa~trusty) ...
Processing triggers for ufw (0.34~rc-0ubuntu2) ...
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up libluajit-5.1-common (2.0.2+dfsg-1) ...
Setting up libluajit-5.1-2:amd64 (2.0.2+dfsg-1) ...
Setting up nginx-common (1.6.2-2ppa~trusty) ...
Processing triggers for ufw (0.34~rc-0ubuntu2) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up nginx-custom (1.6.2-2ppa~trusty) ...
Processing triggers for libc-bin (2.19-0ubuntu6.5) ...
Reload : nginx     [OK]
HTTP Auth User Name: easyengine
HTTP Auth Password : b4YpM0
Successfully installed packages
~> sudo ee stack status                               
nginx     :  Running
php5-fpm  :  Running
mysql     :  Running
~> sudo ee site create example.com --html
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Reload : nginx     [OK]
Successfully created site http://example.com
```

I definitely need to revert to docker or vagrant :-)

Thank you.

**Comment by lrkwz** [comment]
I'll suggest to:

* check nginx version during install
* drop a fancy index.html in htdocs :-)

good job!

**Comment by rahul286** [comment]
@gau1991 I agree with @lrkwz 

We must check for existing version of packages that EE installs. A step ahead, we may ask if admin wants EE to remove old packages.
