### ISSUE TITLE
Reload : nginx     [Failed], Unable to change owner : /var/www/example.com

### ISSUE THREAD

**Issue by w33zy** [rtCamp/easyengine#439]
I am running EE 3.0.2, recently installed. I started by creating a site using EE then, I followed the tutorials to switch to HHVM. The site is running OK, however now I am getting errors when I try to created a new site.

    root@rosetta:~# ee site create example.com --wpfc
    Setting up NGINX configuration  [Done]
    Setting up webroot              [Done]
    Downloading Wordpress           [Done]
    Setting up database             [Done]
    Reload : nginx     [Failed]
    Unable to change owner : /var/www/example.com

**Comment by w33zy** [comment]
Please close this issue. There was something wrong with my nginx config

**Comment by ddelaey** [comment]
@w33zy
It would be handy to know for others what you did wrong I guess.

I would be interested what exact steps you used to switch to HHVM and if you have figures on the effect on speed and memory. Can you share? Do you use SSL too? Thanks :-)

**Comment by gau1991** [comment]
@w33zy ,
Can you give me output of `nginx -t` command?

**Comment by harshadyeola** [comment]
@w33zy @ddelaey 
```ee site create example.com ```  does not proceed unless it finds nginx configurations working.
I am closing this issue.
