### ISSUE TITLE
EE mail stack, MIME issue?

### ISSUE THREAD

**Issue by ddelaey** [rtCamp/easyengine#440]
I EE3.0.2 installed with mail support.

When sending an email from gmail to the EE email server, it arrives fine and I can see it in the webmail on my server.

However, when I send an email from my Mac with MacOutlook, I get the following error message via email back:

User-Agent: Microsoft-MacOutlook/14.4.7.141117
Mime-version: 1.0
Content-type: multipart/alternative;
	boundary="B_3507481356_20752762"
This message is in MIME format. Since your mail reader does not understand
this format, some or all of this message may not be legible.
--B_3507481356_20752762
Content-type: text/plain;
	charset="US-ASCII"
Content-transfer-encoding: 7bit
Test 3
--B_3507481356_20752762
Content-type: text/html;
	charset="US-ASCII"
Content-transfer-encoding: quoted-printable
<html><head></head><body style=3D"word-wrap: break-word; -webkit-nbsp-mode: s=
pace; -webkit-line-break: after-white-space; color: rgb(0, 0, 0); font-size:=
14px; font-family: Calibri, sans-serif;"><div>Test 3</div></body></html>
--B_3507481356_20752762--

What's wrong? Is there something that needs to be enabled? Or installed extra?

IP: 185.53.169.64
Debian 7.8

**Comment by harshadyeola** [comment]
@ddelaey 

need to check this, will update you soon over this issue.

**Comment by ddelaey** [comment]
@harshadyeola

An email sent from an Android device also gives an issue.

>>>
This message was created automatically by mail delivery software.
A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64

VGVzdAo=
<<<

Sending an email from an outlook exchange webmail is received okay, same for gmail.

**Comment by ddelaey** [comment]
Anyone an idea what could be wrong?

**Comment by rahul286** [comment]
@ddelaey we haven't faced issue during our test. If it's solve for you then its fine.

Otherwise please use community support forum at - http://community.rtcamp.com/c/easyengine 

Please check more details at - https://github.com/rtCamp/easyengine/blob/master/CONTRIBUTING.md
