### ISSUE TITLE
EE Site Create Issue

### ISSUE THREAD

**Issue by tareq1988** [rtCamp/easyengine#442]
I think there is some bug when creating a site. Here's the command below I tried:

`root@vps:~# ee site create test.example.com --wpfc`

**Output:**
Setting up NGINX configuration  [Done]
Setting up webroot      [Done]
Downloading Wordpress       [Done]
Setting up database     [Done]
Reload : nginx     [OK]
WordPress admin user : Tareq Hasan
WordPress admin user password : ******
Configure nginx-helper: http://test.example.com/wp-admin/options-general.php?page=nginx
Configure W3TC:     http://test.example.com/wp-admin/admin.php?page=w3tc_general
Page Cache:     Disable
Database Cache:     Memcached
Object Cache:       Memcached
Browser Cache:      Disable
Successfully created site http://test.example.com

**Result:**
WordPress was installed. By going to the URL, I saw the installation screen with **Language Selection** prompt. The next screen was site title and admin user creation screen. 

**What I expected**:
 - WordPress should have been installed with that given user and password details
 - Nginx-helper plugin should've been installed, but it didn't.
 - I didn't mention W3TC plugin, why it's showing there in the command output. No idea. Even it wasn't installed.
 - Also Database cache and object cache wasn't installed

**Comment by harshadyeola** [comment]
@tareq1988 
Yes its bug, please post your ```cat /var/log/ee/ee.log``` for furthur debugging
**Possible Reasons**
It may have been caused due to invalid  email format you have set in your git config, or ee.conf file
 Above command installs w3tc for memcache and object cache
As wordpress did not install, it did not install plugins

**Comment by tareq1988** [comment]
Yeah, seems like I got the error. In wp-cli, this was passing:
`--admin_name=Tareq Hasan` and it was failing because of the space in name. May be it should be passed like this? `--admin_name="Tareq Hasan"`

**Comment by harshadyeola** [comment]
@tareq1988 
Yup, Thanks. This will be fixed soon.
