### ISSUE TITLE
ViMbAdmin timezone issue

### ISSUE THREAD

**Issue by ddelaey** [rtCamp/easyengine#446]
While trying EE 3.0.4 on a new VPS I'm getting the following:

( ! ) Warning: strftime(): Invalid date.timezone value 'CEST', we selected the timezone 'UTC' for now. in /var/www/22222/htdocs/vimbadmin/library/ViMbAdmin/Smarty/functions/modifier.date_formatter.php on line 61
Call Stack
#	Time	Memory	Function	Location
1	0.0000	235912	{main}( )	.../index.php:0
2	0.0207	1989752	Zend_Application->run( )	.../index.php:34
3	0.0207	1989872	Zend_Application_Bootstrap_Bootstrap->run( )	.../Application.php:382
4	0.0207	1991344	Zend_Controller_Front->dispatch( )	.../Bootstrap.php:105
5	0.0215	2121176	Zend_Controller_Dispatcher_Standard->dispatch( )	.../Front.php:954
6	0.0256	2507872	Zend_Controller_Action->dispatch( )	.../Standard.php:308
7	0.0472	4469624	Zend_Controller_Action_HelperBroker->notifyPostDispatch( )	.../Action.php:527
8	0.0473	4470672	Zend_Controller_Action_Helper_ViewRenderer->postDispatch( )	.../HelperBroker.php:277
9	0.0473	4470960	Zend_Controller_Action_Helper_ViewRenderer->render( )	.../ViewRenderer.php:965
10	0.0477	4472024	Zend_Controller_Action_Helper_ViewRenderer->renderScript( )	.../ViewRenderer.php:926
11	0.0477	4472120	OSS_View_Smarty->render( )	.../ViewRenderer.php:905
12	0.0477	4476304	Smarty_Internal_TemplateBase->fetch( )	.../Smarty.php:300
13	0.0481	4518624	content_54f4cf95bd6600_47695062( )	.../smarty_internal_templatebase.php:182
14	0.0566	4745840	smarty_function_tmplinclude( )	.../30ae483e0fc1bc23328c1ec133190dcccb6bcb2d.file.setup.phtml.php:135
15	0.0569	4749712	Smarty_Internal_TemplateBase->fetch( )	.../function.tmplinclude.php:113
16	0.0570	4778504	content_54f4cf9612d275_72794252( )	.../smarty_internal_templatebase.php:182
17	0.0571	4779024	smarty_modifier_date_formatter( )	.../9b5537f93ed09a3c3e8861765f199de86ec054be.file.footer.phtml.php:35
18	0.0571	4779984	strftime ( )	.../modifier.date_formatter.php:61

How can this be solved?

**Comment by gau1991** [comment]
Hi....
It look like error in your PHP timezone,Have you changed it?
Also can you give output of following commands?

```
date
grep -Hr timezone /etc/php5
```

**Comment by ddelaey** [comment]
It was a default install of the VPS. I did not change anything to CEST.
In an attempt to solve the issue I tried: "TZ='Europe/Brussels'; export TZ", but that did not solve the PHP issue obviously.

root@149-210-145-105:~# date
Tue Mar  3 07:39:44 CET 2015

root@149-210-145-105:~# grep -Hr timezone /etc/php5
/etc/php5/fpm/php.ini:date.timezone = CEST
/etc/php5/cgi/php.ini:; Defines the default timezone used by the date functions
/etc/php5/cgi/php.ini:; http://php.net/date.timezone
/etc/php5/cgi/php.ini:;date.timezone =
/etc/php5/cli/php.ini:; Defines the default timezone used by the date functions
/etc/php5/cli/php.ini:; http://php.net/date.timezone
/etc/php5/cli/php.ini:;date.timezone =

**Comment by gau1991** [comment]
You need to do edit
```
vim /etc/php5/fpm/php.ini
```
In this file  you need to set  timezone as per http://php.net/manual/en/timezones.php
After that
```
service php5-fpm restart
```
