### ISSUE TITLE
ee log - more subcommands needed

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#448]
`ee log show` => same as `ee log` we have now
`ee log reset` => run  `> log.file` on selected files. Special case `--slow-log--db` will drop all rows from slowlog table in database
`ee log zip` => will zip selected log files
`ee log email --to=A --to=B` => will email selected log files to A and B

**Comment by harshadyeola** [comment]
Added in EasyEngine 3.1.0, Please update your EasyEngine.
