### ISSUE TITLE
Documentation link for migrate displays 404 error

### ISSUE THREAD

**Issue by texgibson** [rtCamp/easyengine#452]
In the documentation for the site commands here http://docs.rtcamp.com/easyengine/commands/site/ if you click the migrate link it will bring you to a 404 page.

**Comment by gau1991** [comment]
Hello @texgibson ,
Thanks for pointing this.
Migrate command is not yet ready. We now removed that from doc.
Ref: https://github.com/rtCamp/docs.rtcamp.com/commit/6d03c486a8d1cb67541af41862f8fab881f282be
