### ISSUE TITLE
Upgrade causes issue with mysql password.

### ISSUE THREAD

**Issue by irazasyed** [rtCamp/easyengine#454]
Hi,

I updated my installation from 2 (I think so, can't remember what version i had previously) to 3.x recently and it seems like, it for some reason updated the `.my.cnf` file with a new mysql password (It already had previous login credentials), making the script and mysql from command line inaccessible (Due to wrong password of course).

So whenever i tried to create a new site using the standard commands, it always ended up throwing `Cannot create database` error. Thankfully i had Sequel Pro connected to mysql already, I updated root user's password from it based on the `.my.cnf` file and it started working fine. So i assume when the update was happening, it randomly generated the password and updated the file which in fact it shouldn't be doing that. Please take a look.

Thanks!

**Comment by gau1991** [comment]
Hello @irazasyed ,
While updating EasyEngine 2.x to 3.x, it never updates MySQL password. 
Can you please make sure that your `.my.cnf` is at location `~/.my.cnf` ?

**Comment by irazasyed** [comment]
Hi @gau1991 ,

Well, then I'm not sure when it changed but it did change the password (The password wasn't changed for real, it simply changed in `~/.my.cnf` but not the actual account password).

And yes, he file is located at `~/.my.cnf` because it had wrong password, the command line program wouldn't work but i was able to connect from Sequel Pro just fine (I had saved with original/old credentials).

**Comment by rahul286** [comment]
@irazasyed if you are still facing issue, you may reset mysql root password and update `~/.my.cnf` with revised password.

For technical support, please use free community support - http://community.rtcamp.com/c/easyengine 

We are also offering premium support at https://rtcamp.com/products/easyengine-premium-support/

Please read for more details - https://github.com/rtCamp/easyengine/blob/master/CONTRIBUTING.md
