### ISSUE TITLE
FRESH DROPLET Unable to clean OpCache

### ISSUE THREAD

**Issue by shaneholloman** [rtCamp/easyengine#456]
On a fresh droplet and EE installation

```
root@loophole:/var/www/loophole.io# ee clean --all
Restart : memcached [OK]
Cleaning MemCache
Cleaning NGINX FastCGI cache
Cleaning opcache
Unable to clean OpCache
root@loophole:/var/www/loophole.io#
```

**Comment by harshadyeola** [comment]
Plz Check if you have installed admin tools first , if not then install them with `ee stack install --admin` command. and then you can use `ee clean --all` command

**Comment by shaneholloman** [comment]
@harshadyeola that was it! Simple solve. Thank you

**Comment by nautinz** [comment]
Could there be another solve? I have the same problem and ee stack install --admin has been initiated already, so for good measure I ran gain - still the notice persists
