### ISSUE TITLE
FRESH DROPLET clean default fast cgi wordpress config is very slow and memory intensive

### ISSUE THREAD

**Issue by shaneholloman** [rtCamp/easyengine#457]
A single page call on a 2GB droplet consume 50-85% of a single CPU... this is waay to much.

Can you please provide good working default config files here please and where to place them. Thank you

**Comment by gau1991** [comment]
@shaneholloman ,
On which VPS you were testing?
We did EasyEngine 3.x testing from 512MB DO instance, but never occurred high RAM utilization

**Comment by shaneholloman** [comment]
@gau1991 using the Digital Ocean 14.04 2GB and added a 4GB swap

**Comment by gau1991** [comment]
@shaneholloman ,
> A single page call on a 2GB droplet consume 50-85% of a single CPU... this is waay to much.
This may be cause beacuse of bad plugin or theme also.
Can you please  try with disbaling all pugins and with using default wordpress theme?

**Comment by rahul286** [comment]
For technical support, please use free community support - http://community.rtcamp.com/c/easyengine 

We are also offering premium support at https://rtcamp.com/products/easyengine-premium-support/

Please read for more details - https://github.com/rtCamp/easyengine/blob/master/CONTRIBUTING.md

**Comment by shaneholloman** [comment]
Im aware of these links, I have paid you a couple of times now for help from those... this appeared to be an issue to me, therefore my post

**Comment by rahul286** [comment]
Its about paid or free. We repeatedly told everyone to use community forum for support request which is here - http://community.rtcamp.com/c/easyengine

This is new thing - https://rtcamp.com/products/easyengine-premium-support/ (not the link you have used before). We did not have premium support option few days back.

Anyway, we will not be giving any support here on github issue tracker. If we realize a bug is present during any discussion on free community forum or paid support helpdesk - we will create an issue ourselve. 

We are dividing our team into development team and support team so everyone can focus on one aspect of EasyEngine. To speed up development, one of the things we need is keep this github issue tracker clean so we can think of every github issue as "development task" as opposed to "support ticket".

About your current issue, if you are facing performance issue, even with default WordPress setup _(no themes or plugin)_, then please continue discussion on http://community.rtcamp.com/c/easyengine
