### ISSUE TITLE
ee stack update?

### ISSUE THREAD

**Issue by rippler** [rtCamp/easyengine#458]
I looked around but couldn't see a way to update stack components that are kept back from system updates (e.g. nginx).
Those who would like to update system pacakges, what are the options?
(I don't know if updating EasyEngine to v3.x "solves" this requirement, but there will always be situations where stack packages will be updated before EasyEngine, so I'm hoping for a solution that is least intrusive, something like `ee stack update` might be).

**Comment by rahul286** [comment]
Lets run apt-get upgrade behind the scene with a flag to avoid overwriting config files.

Command can be named `ee stack upgrade` to match `apt-get upgrade`

**Comment by JosefJezek** [comment]
@rahul286 Could you add support for update config files using git merge? How to check config files changes in ee?
