### ISSUE TITLE
Fastcgi cache cookie issue?

### ISSUE THREAD

**Issue by matthewkeath** [rtCamp/easyengine#459]
Hi,

Getting a lot of errors on a recent site. Please find log below:

_______________

Server: nginx

Date: Mon, 16 Mar 2015 06:55:48 GMT

Content-Type: application/json; charset=UTF-8

Transfer-Encoding: chunked

Connection: keep-alive

Vary: Accept-Encoding

Access-Control-Allow-Origin: http://www.blackjacknights.com.au

Access-Control-Allow-Credentials: true

X-Robots-Tag: noindex

X-Content-Type-Options: nosniff

Expires: Wed, 11 Jan 1984 05:00:00 GMT

Cache-Control: no-cache, must-revalidate, max-age=0

Pragma: no-cache

X-Frame-Options: SAMEORIGIN

X-Powered-By: EasyEngine 2.2.1

Vary: Accept-Encoding

Content-Encoding: gzip

2015/03/16 17:55:48 [debug] 29260#0: *744737 write new buf t:1 f:0 0000000004015F20, pos 0000000004015F20, size: 572 file: 0, size: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 http write filter: l:0 f:0 s:572
2015/03/16 17:55:48 [debug] 29260#0: *744737 http script var: "1"
2015/03/16 17:55:48 [debug] 29260#0: *744737 http cacheable: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 http upstream process upstream
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe read upstream: 1
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe preread: 67
2015/03/16 17:55:48 [debug] 29260#0: *744737 readv: 1:32344
2015/03/16 17:55:48 [debug] 29260#0: *744737 readv() not ready (11: Resource temporarily unavailable)
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe recv chain: -2
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe buf free s:0 t:1 f:0 0000000003F84660, pos 0000000003F847C5, size: 67 file: 0, size: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe length: -1
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe write downstream: 1
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe write busy: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe write: out:0000000000000000, f:0
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe read upstream: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe buf free s:0 t:1 f:0 0000000003F84660, pos 0000000003F847C5, size: 67 file: 0, size: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe length: -1
2015/03/16 17:55:48 [debug] 29260#0: *744737 event timer del: 202: 1426489247464
2015/03/16 17:55:48 [debug] 29260#0: *744737 event timer add: 202: 300000:1426489248135
2015/03/16 17:55:48 [debug] 29260#0: *744737 post event 00000000049BA7F8
2015/03/16 17:55:48 [debug] 29260#0: *744737 post event 000000000370DD88
2015/03/16 17:55:48 [debug] 29260#0: *744737 delete posted event 000000000370DD88
2015/03/16 17:55:48 [debug] 29260#0: *744737 http upstream request: "/wp-admin/admin-ajax.php?"
2015/03/16 17:55:48 [debug] 29260#0: *744737 http upstream dummy handler
2015/03/16 17:55:48 [debug] 29260#0: *744737 delete posted event 00000000049BA7F8
2015/03/16 17:55:48 [debug] 29260#0: *744737 http upstream request: "/wp-admin/admin-ajax.php?"
2015/03/16 17:55:48 [debug] 29260#0: *744737 http upstream process upstream
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe read upstream: 1
2015/03/16 17:55:48 [debug] 29260#0: *744737 readv: 1:32344
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe recv chain: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe buf free s:0 t:1 f:0 0000000003F84660, pos 0000000003F847C5, size: 67 file: 0, size: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe length: -1
2015/03/16 17:55:48 [debug] 29260#0: *744737 input buf #0 0000000003F847C5
2015/03/16 17:55:48 [debug] 29260#0: *744737 http fastcgi record byte: 01
2015/03/16 17:55:48 [debug] 29260#0: *744737 http fastcgi record byte: 03
2015/03/16 17:55:48 [debug] 29260#0: *744737 http fastcgi record byte: 00
2015/03/16 17:55:48 [debug] 29260#0: *744737 http fastcgi record byte: 01
2015/03/16 17:55:48 [debug] 29260#0: *744737 http fastcgi record byte: 00
2015/03/16 17:55:48 [debug] 29260#0: *744737 http fastcgi record byte: 08
2015/03/16 17:55:48 [debug] 29260#0: *744737 http fastcgi record byte: 00
2015/03/16 17:55:48 [debug] 29260#0: *744737 http fastcgi record byte: 00
2015/03/16 17:55:48 [debug] 29260#0: *744737 http fastcgi record length: 8
2015/03/16 17:55:48 [debug] 29260#0: *744737 http fastcgi sent end request
2015/03/16 17:55:48 [debug] 29260#0: *744737 input buf 0000000003F847C5 47
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe write downstream: 1
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe write downstream flush in
2015/03/16 17:55:48 [debug] 29260#0: *744737 http output filter "/wp-admin/admin-ajax.php?"
2015/03/16 17:55:48 [debug] 29260#0: *744737 http copy filter: "/wp-admin/admin-ajax.php?"
2015/03/16 17:55:48 [debug] 29260#0: *744737 image filter
2015/03/16 17:55:48 [debug] 29260#0: *744737 xslt filter body
2015/03/16 17:55:48 [debug] 29260#0: *744737 http postpone filter "/wp-admin/admin-ajax.php?" 0000000004042B00
2015/03/16 17:55:48 [debug] 29260#0: *744737 http gzip filter
2015/03/16 17:55:48 [debug] 29260#0: *744737 malloc: 0000000003FB9C00:270336
2015/03/16 17:55:48 [debug] 29260#0: *744737 gzip alloc: n:1 s:5936 a:8192 p:0000000003FB9C00
2015/03/16 17:55:48 [debug] 29260#0: *744737 gzip alloc: n:32768 s:2 a:65536 p:0000000003FBBC00
2015/03/16 17:55:48 [debug] 29260#0: *744737 gzip alloc: n:32768 s:2 a:65536 p:0000000003FCBC00
2015/03/16 17:55:48 [debug] 29260#0: *744737 gzip alloc: n:32768 s:2 a:65536 p:0000000003FDBC00
2015/03/16 17:55:48 [debug] 29260#0: *744737 gzip alloc: n:16384 s:4 a:65536 p:0000000003FEBC00
2015/03/16 17:55:48 [debug] 29260#0: *744737 gzip in: 0000000003E727A8
2015/03/16 17:55:48 [debug] 29260#0: *744737 gzip in_buf:0000000003E726E0 ni:0000000003F847C5 ai:47
2015/03/16 17:55:48 [debug] 29260#0: *744737 malloc: 0000000003FFBC10:8192
2015/03/16 17:55:48 [debug] 29260#0: *744737 deflate in: ni:0000000003F847C5 no:0000000003FFBC10 ai:47 ao:8192 fl:0 redo:0
2015/03/16 17:55:48 [debug] 29260#0: *744737 deflate out: ni:0000000003F847F4 no:0000000003FFBC10 ai:0 ao:8192 rc:0
2015/03/16 17:55:48 [debug] 29260#0: *744737 gzip in_buf:0000000003E726E0 pos:0000000003F847C5
2015/03/16 17:55:48 [debug] 29260#0: *744737 gzip in: 0000000000000000
2015/03/16 17:55:48 [debug] 29260#0: *744737 http copy filter: 0 "/wp-admin/admin-ajax.php?"
2015/03/16 17:55:48 [debug] 29260#0: *744737 pipe write downstream done
2015/03/16 17:55:48 [debug] 29260#0: *744737 event timer: 202, old: 1426489248135, new: 1426489248135
2015/03/16 17:55:48 [debug] 29260#0: *744737 http upstream exit: 0000000000000000
2015/03/16 17:55:48 [debug] 29260#0: *744737 finalize http upstream request: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 finalize http fastcgi request
2015/03/16 17:55:48 [debug] 29260#0: *744737 free rr peer 1 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 close http upstream connection: 202
2015/03/16 17:55:48 [debug] 29260#0: *744737 free: 0000000002CF5850, unused: 48
2015/03/16 17:55:48 [debug] 29260#0: *744737 event timer del: 202: 1426489248135
2015/03/16 17:55:48 [debug] 29260#0: *744737 reusable connection: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 http upstream temp fd: -1
2015/03/16 17:55:48 [debug] 29260#0: *744737 http output filter "/wp-admin/admin-ajax.php?"
2015/03/16 17:55:48 [debug] 29260#0: *744737 http copy filter: "/wp-admin/admin-ajax.php?"
2015/03/16 17:55:48 [debug] 29260#0: *744737 image filter
2015/03/16 17:55:48 [debug] 29260#0: *744737 xslt filter body
2015/03/16 17:55:48 [debug] 29260#0: *744737 http postpone filter "/wp-admin/admin-ajax.php?" 00007FFF1BECB0D0
2015/03/16 17:55:48 [debug] 29260#0: *744737 http gzip filter
2015/03/16 17:55:48 [debug] 29260#0: *744737 gzip in: 0000000004016200
2015/03/16 17:55:48 [debug] 29260#0: *744737 gzip in_buf:00000000040161B0 ni:0000000000000000 ai:0
2015/03/16 17:55:48 [debug] 29260#0: *744737 deflate in: ni:0000000000000000 no:0000000003FFBC10 ai:0 ao:8192 fl:4 redo:0
2015/03/16 17:55:48 [debug] 29260#0: *744737 deflate out: ni:0000000000000000 no:0000000003FFBC41 ai:0 ao:8143 rc:1
2015/03/16 17:55:48 [debug] 29260#0: *744737 gzip in_buf:00000000040161B0 pos:0000000000000000
2015/03/16 17:55:48 [debug] 29260#0: *744737 free: 0000000003FB9C00
2015/03/16 17:55:48 [debug] 29260#0: *744737 http chunk: 10
2015/03/16 17:55:48 [debug] 29260#0: *744737 http chunk: 57
2015/03/16 17:55:48 [debug] 29260#0: *744737 write old buf t:1 f:0 0000000004015F20, pos 0000000004015F20, size: 572 file: 0, size: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 write new buf t:1 f:0 0000000004016300, pos 0000000004016300, size: 4 file: 0, size: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 write new buf t:0 f:0 0000000000000000, pos 00000000014007E0, size: 10 file: 0, size: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 write new buf t:1 f:0 0000000003FFBC10, pos 0000000003FFBC10, size: 57 file: 0, size: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 write new buf t:0 f:0 0000000000000000, pos 0000000000D08218, size: 7 file: 0, size: 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 http write filter: l:1 f:1 s:650
2015/03/16 17:55:48 [debug] 29260#0: *744737 http write filter limit 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 writev: 650
2015/03/16 17:55:48 [debug] 29260#0: *744737 http write filter 0000000000000000
2015/03/16 17:55:48 [debug] 29260#0: *744737 http copy filter: 0 "/wp-admin/admin-ajax.php?"
2015/03/16 17:55:48 [debug] 29260#0: *744737 http finalize request: 0, "/wp-admin/admin-ajax.php?" a:1, c:1
2015/03/16 17:55:48 [debug] 29260#0: *744737 set http keepalive handler
2015/03/16 17:55:48 [debug] 29260#0: *744737 http close request
2015/03/16 17:55:48 [debug] 29260#0: *744737 http log handler
2015/03/16 17:55:48 [debug] 29260#0: *744737 free: 0000000003FFBC10
2015/03/16 17:55:48 [debug] 29260#0: *744737 free: 0000000000000000
2015/03/16 17:55:48 [debug] 29260#0: *744737 free: 0000000003F84660
2015/03/16 17:55:48 [debug] 29260#0: *744737 free: 0000000003F906D0, unused: 2
2015/03/16 17:55:48 [debug] 29260#0: *744737 free: 0000000004041E70, unused: 8
2015/03/16 17:55:48 [debug] 29260#0: *744737 free: 0000000003E717D0, unused: 8
2015/03/16 17:55:48 [debug] 29260#0: *744737 free: 0000000004015F00, unused: 2501
2015/03/16 17:55:48 [debug] 29260#0: *744737 free: 00000000035F1B40
2015/03/16 17:55:48 [debug] 29260#0: *744737 hc free: 0000000000000000 0
2015/03/16 17:55:48 [debug] 29260#0: *744737 hc busy: 0000000003E72978 1
2015/03/16 17:55:48 [debug] 29260#0: *744737 free: 0000000003724930
2015/03/16 17:55:48 [debug] 29260#0: *744737 tcp_nodelay
2015/03/16 17:55:48 [debug] 29260#0: *744737 reusable connection: 1
2015/03/16 17:55:48 [debug] 29260#0: *744737 event timer add: 200: 15000:1426488963135
2015/03/16 17:55:48 [debug] 29260#0: *744737 post event 00000000049B8298
2015/03/16 17:55:48 [debug] 29260#0: *744737 delete posted event 00000000049B8298
2015/03/16 17:55:48 [debug] 29260#0: *744737 http keepalive handler
2015/03/16 17:55:48 [debug] 29260#0: *744737 malloc: 00000000035F1B40:1024
2015/03/16 17:55:48 [debug] 29260#0: *744737 recv: fd:200 -1 of 1024
2015/03/16 17:55:48 [debug] 29260#0: *744737 recv() not ready (11: Resource temporarily unavailable)
2015/03/16 17:55:48 [debug] 29260#0: *744737 free: 00000000035F1B40

**Comment by shaneholloman** [comment]
@matthewkeath  WOW!!! your is site FAST!! I mean REALLY fast!

**Comment by harshadyeola** [comment]
@matthewkeath 
It seems that you have started nginx debug mode.
To stop it you can use `ee debug --nginx --stop`

**Comment by matthewkeath** [comment]
The problem is that then I have not solved the problem? This and another site are getting heaps of these errors and it's crashing the backend of WordPress.

**Comment by rahul286** [comment]
@matthewkeath it could be theme/plugin issue. 

Try debugging PHP/WordPress `ee debug example.com --php --wp`

Please use http://community.rtcamp.com/c/easyengine for support requests.
