### ISSUE TITLE
Possible Bug used by Malware?

### ISSUE THREAD

**Issue by duajanuari** [rtCamp/easyengine#460]
Hello

I've recomended Easy Engine to many of my friends, most of them are web freelancers. Some of them are complaining one ore more of their node/droplets/vps are suspended by their service providers cause traffic flooding. Most of them are use Digital Ocean.

I myself though not being able to reproduce the issue, have experienced same thing. One of my Linode are used 700GB only for 1 day. There's fresh deploy with Easy Engine. Too bad, I'm destroyed that node cause it eat up my resources, especially bandwidth before I examine em.

Possible issue(s) in my opinion are:
1. port 22222 utilities
2. memcached
3. I don't know if I'm unlucky, and use compromised droplets ip since service providers are reuse ip when destroyed

Any ideas or anyone have audited Easy Engine's security?

**Comment by rahul286** [comment]
We never faced any issues like that. 700GB is too much for a day. 

Please check if affected droplet was having any email delivery issue. 

Here is rtcamp.com usage

![linode_-_dashboard____li-rtcamp-com](https://cloud.githubusercontent.com/assets/4115/6706311/525f1738-cd82-11e4-85d7-72ab8a52bc66.png)

**Comment by gau1991** [comment]
Hello @duajanuari ,
> Some of them are complaining one ore more of their node/droplets/vps are suspended by their service providers cause traffic flooding. Most of them are use Digital Ocean.

We never experince this problem on any of our droplet. We use Digital Ocean, Linode and Amazone for our server hosting as well as EasyEngine testing.

> 1. port 22222 utilities

By deafult EasyEngine uses HTTP auth for 22222 port, so no one can access it without the password

>  2. memcached

Memcache also listens to only 127.0.0.1 reuqests, so other outside IP are not possible to communitcate with Memcache.

>  3. I don't know if I'm unlucky, and use compromised droplets ip since service providers are reuse ip when destroyed

This might issue but I am not sure.

You can figure out traffice flooding by using utilities like `iftop` and `goaccess` . I will also recomemnded you to disable port in `iptables` that you are not using.
