### ISSUE TITLE
VSFTPD - Virtual Users

### ISSUE THREAD

**Issue by benzon** [rtCamp/easyengine#463]
First of all thanks for bringing EasyEngine to us!

Followed and used the project for quite some time now, and love the way it's going and the direction the development has taken.

The only thing I hate, is that EasyEngine dos not give us a way to give a user FTP Access, we only got the www-data SFTP login, I got a couple of costumers that need FTP access, and I dont want to hand out the www-data user, since they can do to mutch harm.

So I started my journey how could I make a solution that worked with EasyEngine, and that allowed me to create FTP accounts for specific websites, with out giving them access to all other websites on the server.

After some searching on Virtual Users FTP, I tried out a couple of tutorials and it worked! BUT! They used text files, and raw passwords, not very safe to be honest, so when I got a new server I played arround with VSFTPD/MySQL and PAM, to create a more secure container for the password, and to be honest it's just a better way then creating text files to get the same result.

The guides found for VSFTPD/MySQL/PAM and Virtual Users, did not work out that well, because they forgot to mention, that Ubuntu got meny problems with VSFTPD true apt-get, after a lot of searching I finally found a good forum thread on UbuntuForums.

First we need to get a working version of VSFTPD! http://ehcpforce.tk/faq/index.php?sid=2579&lang=en&action=artikel&cat=1&id=3&artlang=en this link contains info for Ubuntu 12.04 and above, and is different for every Version of Ubuntu.

After you installed VSFTPD follow the following guide.
apt-get install libpam-mysql libpam-ldap

LDAP server Uniform Resource Identifier: <--  ENTER
Distinguished name of the search base: <-- ENTER
LDAP version to use: <-- 3
Make local root Database admin: <-- Yes
Does the LDAP database require login?  <-- No
LDAP account for root: <-- ENTER
LDAP root account password: <-- ldaprootpw (change to your password)

If you get more questions select the option that it surgests

==> Create The MySQL Database For vsftpd
mysql -u root -p

==> Create the Database, and user, remember to set your own password instead of fpdpass
CREATE DATABASE vsftpd;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP ON vsftpd.* TO 'vsftpd'@'localhost' IDENTIFIED BY 'ftpdpass';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP ON vsftpd.* TO 'vsftpd'@'localhost.localdomain' IDENTIFIED BY 'ftpdpass';
FLUSH PRIVILEGES;
USE vsftpd;

==> Create the Tables in vsftpd Database
USE vsftpd; 
CREATE TABLE `accounts` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`username` VARCHAR( 30 ) NOT NULL ,
`pass` VARCHAR( 50 ) NOT NULL ,
UNIQUE (
`username`
)
) ENGINE = MYISAM ; 
quit; 

==> Only use this line if you got issues with the setup, I only tested with this line, since I had some issues, that I later found out was Ubuntus version of VSFTPD
useradd --home /home/vsftpd --gid nogroup -m --shell /bin/false vsftpd 

==> Config file stuff
cp /etc/vsftpd.conf /etc/vsftpd.conf_orig
cat /dev/null > /etc/vsftpd.conf
nano /etc/vsftpd.conf 

==> Insert following to the config file
listen=YES
anonymous_enable=NO
local_enable=YES
virtual_use_local_privs=YES
write_enable=YES
local_umask=022
connect_from_port_20=YES
secure_chroot_dir=/var/run/vsftpd
pam_service_name=vsftpd
guest_enable=YES
ftp_username=www-data
chown_username=www-data
guest_username=www-data
user_sub_token=$USER
local_root=/var/www/$USER
chroot_local_user=YES
hide_ids=YES
check_shell=NO
user_config_dir=/var/www/users
allow_writeable_chroot=YES

==> Create user_config_dir
mkdir /var/www/users 

==> Lets create the PAM config files for vsftpd
cp /etc/pam.d/vsftpd /etc/pam.d/vsftpd_orig
cat /dev/null > /etc/pam.d/vsftpd
nano /etc/pam.d/vsftpd 

==> Insert the following, remember to change ftpdpass in to the password you set for the mysql vsftpd user earlyer
auth required pam_mysql.so user=vsftpd passwd=ftpdpass host=localhost db=vsftpd table=accounts usercolumn=username passwdcolumn=pass crypt=2
account required pam_mysql.so user=vsftpd passwd=ftpdpass host=localhost db=vsftpd table=accounts usercolumn=username passwdcolumn=pass crypt=2

==> Restart VSFTPD
/etc/init.d/vsftpd restart 

==> Create the first virtual user, remember the username needs to match a folder in /var/www ex. Domain.com
mysql -u root -p 
USE vsftpd; 

==> Remember to change domain.com and password to what you want
INSERT INTO accounts (username, pass) VALUES('testuser', PASSWORD('secret'));
quit; 

–--------------------------------

You should now be good to go, and have a working ftp user that can only access /var/www/domain.com

If you want a user to have a different root, or create a “master” account, you can do this by creating a file in /var/www/users

Example – the file you create inside /var/www/users needs to match the username, lets say I created a username thats masteruser in the mysql table

nano /var/www/users/masteruser

==>> Insert the following change the directory to /var/www or something inside /var/www
Example 1
local_root=/var/www

Example 2
local_root=/var/www/domain.com

**Comment by benzon** [comment]
Hope we can get some sort of adoptation in to EasyEngine, since this would fit it perfectly! Easy Simple, and Works like intended!

Created it as a tutorial in the EasyEngine Forum
http://community.rtcamp.com/t/vsftpd-mysql-virtual-users-tutorial/4228

**Comment by benzon** [comment]
Minor note if you install libpam-mysql and then update to MariaDB you need to install libpam-mysql once more.

**Comment by gau1991** [comment]
@benzon ,
We always recomend to use SFTP instead of vsftpd. 
You can refer https://rtcamp.com/easyengine/docs/chroot-sftp-easyengine/ article to create Sftp for separate uers.

**Comment by JamesBrOP** [comment]
It's much easier to contact these guys on this web site http://buy.fineproxy.org/eng/ /They've helped very quickly. You say your problem, they say a solution. Support 24/7. Сheap proxy

**Comment by jimtyrro** [comment]
@gau1991 
I tried to follow your tutorial to setup Chroot SFtp but encountered the following issue.
Newly created user ee-user has permission to read/write in this directory: 
`/home/ee-user/example.com`

But after you mount webroot in SFtp home directory with the following command:

`mount --bind /var/www/example.com/htdocs /home/ee-user/example.com/htdocs`

All files and `htdocs` directory has `www-data:www-data` permission, so `ee-user` can't really edit/update any files in `htdocs`.

Am I missing something here? I followed your tutorial a couple of times, same result.

Any help or ideas?

**Comment by MiteshShah** [comment]
@jimtyrro 

On tutorial we first add ee-user to the www-data group

```
root@example.com:~# useradd -G www-data -ms /bin/false ee-user
```

Also when ee-user create any files its save with www-data permision due to [SGID Permission] (https://miteshshah.github.io/linux/basics/advanced-topics-in-users-groups-and-permissions/#for-directory)
```
chmod g+s /var/www/example.com/htdocs/
chmod 775 /var/www/example.com/htdocs
```

**Comment by jimtyrro** [comment]
Hi Mitesh,

Thank you for answering, but it still doesn't work. I tried it twice. Still when I FTP into `/var/www/example.com/htdocs` , `htdocs` and all files inside it have `www-data:www-data` permission and whenever I tried to edit any file although `ee-user` is in `www-data` group I'm getting *permission denied* error.

What should I check? Why is my results are different then yours? Any ideas?

**Comment by jimtyrro** [comment]
You mentioned create file, but I didn't try that, I only tried editing existing files and received *"permission denied"* error.

**Comment by MiteshShah** [comment]
@jimtyrro Refer this how to setup sftp video https://asciinema.org/a/8fo1mtmyohch1w1y17alap59a

Once its setup I'd open filezilla and login with ee-user and upload a screenshot
Refer: https://asciinema.org/a/6p18yike4g8ohgwm9638ix2ew

**Comment by jimtyrro** [comment]
Hi Mitesh,

Sorry to bother you again, I did follow your instructions and whenever I try to upload something I receive **"Permission denied"** error. I tried two different FTP client apps just in case, CyberDuck and Yummy FTP (on Mac), same result. See screenshots below.

What could be wrong here?

![sftp_permission_denied_yummy-ftp](https://cloud.githubusercontent.com/assets/12877886/9899327/b50570d4-5c76-11e5-9cdd-6e7f17370546.jpg)
![sftp_permission_denied_cyberduck](https://cloud.githubusercontent.com/assets/12877886/9899387/0f647886-5c77-11e5-8033-eea307842c83.jpg)

**Comment by MiteshShah** [comment]
@jimtyrro can you tell me which user did you tried ?
ee-user or www-data ?

**Comment by jimtyrro** [comment]
I tried ee-user. I can only upload and delete files in htdocs root folder but cannot edit them, and whenever I try to upload files or edit them in any other folder inside htdocs, e.g. wp-content, etc I get permission denied error.

**Comment by jimtyrro** [comment]
In the tutorial you have these two commands:
`chmod g+s /var/www/example.com/htdocs/`
`chmod 775 /var/www/example.com/htdocs`

first is ending with a slash and the second one doesn't , does it have any impact on permissions?
