### ISSUE TITLE
Broken after upgrade

### ISSUE THREAD

**Issue by dovy** [rtCamp/easyengine#464]
Today I did a `ee update` becuase it's been a while. Now ee is broke for me.

* ee site create demo.redux.io --wpfc
  * Downloading WP-CLI               [Errno 2] No such file or directory: '/usr/bin/wp'

* root@reduxframework:/usr/bin# ee --version
  * EasyEngine v3.0.5
  * Copyright (c) 2015 rtCamp Solutions Pvt. Ltd. 

Any ideas?

**Comment by benzon** [comment]
Wird thought the ee update was removed and you had to use https://rtcamp.com/easyengine/docs/commands/ee-update/

**Comment by benzon** [comment]
Try the following

ee stack install --wpcli

And then try and create a --wpfc site again.

**Comment by dovy** [comment]
root@reduxframework:/var/www# ee stack install --wpcli
Downloading WP-CLI               [Errno 2] No such file or directory: '/usr/bin/wp'

**Comment by dovy** [comment]
Just manually installed wp-cli and all is well with the world.  :)

**Comment by dovy** [comment]
Bah, now I'm getting: 
```
root@reduxframework:/var/www# ee site create demo.redux.io --wpfc
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Downloading Wordpress 		[Done]
Setting up database		[Done]
Unable to Generate wp-config
```

Seems like I just need to re-install.

**Comment by benzon** [comment]
Wird issues you got going, just tryed to update my servers my self, no issues or what so ever :(

**Comment by benzon** [comment]
have you tryed ee stack install --web

**Comment by dovy** [comment]
root@reduxframework:/home# ee stack install --web
Nginx already installed
PHP already installed
MySQL connection is already alive
Postfix is already installed
WP-CLI is already installed


However now it does this:
```
root@reduxframework:/var/log/ee# ee site create demo.redux.io --wpfc
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Downloading Wordpress 		[Done]
Setting up database		Cannot setup database user
```

Which probably means on the upgrade it lost my mysql user/pass. Were are those stored?

**Comment by dovy** [comment]
So I thought it was related to #454. So I made sure and reset the root password to the one listed in ~/.my.cnf. However, the problem still persists.

```
root@reduxframework:~# ee site create demo.redux.io --wpfc
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Downloading Wordpress 		[Done]
Setting up database		Cannot setup database user
```

Do you have an odd command in your most recent version? Do I need to update mysql? I originally had ee setup this server. So I'm confused by these issues.

**Comment by dovy** [comment]
Great. Now my whole server is getting 502 Bad Gateway...

**Comment by dovy** [comment]
Ok, so `ee update` forced a new update to /etc/php5/fpm/pool.d/www.conf. I allowed it to create a new file, thus throwing my server into shock.

Luckily it was smart enough to make a www.conf.dpkg-old backup. I restored that, did a service php-fpm restart and my server started working again.

However, now "cannot create database" or "cannot create database user" keeps happening...

**Comment by dovy** [comment]
ee.log:
```
root@reduxframework:/var/log/ee# tail ee.log 
2015-03-18 23:04:08,358 (DEBUG) ee : Changing directory to /var/www/demo.redux.io/htdocs/
2015-03-18 23:04:08,358 (DEBUG) ee : Running command: wp --allow-root core download
2015-03-18 23:04:09,233 (INFO) ee : [Done]
2015-03-18 23:04:09,234 (INFO) ee : Setting up database		
2015-03-18 23:04:09,234 (DEBUG) ee : Creating databse demo_redux_io
2015-03-18 23:04:09,241 (DEBUG) ee : Executing MySQL statement: create database `demo_redux_io`
2015-03-18 23:04:09,242 (DEBUG) ee : Creating user demo_redux_io
2015-03-18 23:04:09,242 (DEBUG) ee : create user `demo_redux_io`@`localhost` identified by ''
2015-03-18 23:04:09,244 (DEBUG) ee : (1396, "#HY000Operation CREATE USER failed for 'demo_redux_io'@'localhost'")
2015-03-18 23:04:09,244 (ERROR) ee : Cannot setup database user
```

**Comment by benzon** [comment]
Not sure if this is helpfull in any way, try and do ee stack migrate --mariadb

Make sure you got backup of your stuff, but ye if it's nothing big you got on the server, it might be faster to do a re-install.

I would hate reinstalling right now, since i got some quite large sites running.

**Comment by dovy** [comment]
I have a few sites running... I'm worried about crashing.

**Comment by dovy** [comment]
It's not ee. It's all in mysql. Can't create the user accounts after update of the stack...

**Comment by benzon** [comment]
Ye that sound like a pain i the a**

Hope one of the dev's can kick in with some info on this, would be nice to know if it happens to me ad some point.

**Comment by dovy** [comment]
OK, here's the resolution.

If for some reason the creation fails (wp-cli wasn't properly installed via an upgrade), then things linger.

So I had to do the following:
1. Install wp-cli manually since it didn't install via upgrade.
2. Remove the database manually - Even though it said the DB didn't exist, I had to manually delete it.
3. Remove the user manually. If the DB isn't found, ee doesn't search for the user to clean things up.
4. Delete the site and try again.

I think we should have extra checks. Even if it's not in the EE database, we should check if the db or user is there and prompt the user to delete them. It would have solved a whole ton of pain.

Also on creation we should check for an existing user. If there is, create another and go. Don't just error out and leave everything a mess.

Either way, that's the resolution. Not enough error checking in the setup site process.  ;)

**Comment by rippler** [comment]
@dovy what was the ee version from which you updated?

**Comment by dovy** [comment]
I honestly do not know, but here's the log of the update.

https://gist.github.com/dovy/ec94a8f4db1ff280e9a9

**Comment by rippler** [comment]
Thanks. I'll take a snapshot of the VM before I try!

**Comment by dovy** [comment]
I have a backup of my server I may be able to get from linode if you need.

**Comment by gau1991** [comment]
@dovy ,
I would like to check your server if you are not destroyed it yet.
You can add my SSH key fromhere http://docs.rtcamp.com/easyengine/keys.html

**Comment by dovy** [comment]
I will get you access tomorrow. On the road today.

**Comment by MattyLB** [comment]
I just updated from 3.0.3 to 3.0.5 and I'm getting the same "Unable to
Generate wp-config" issue.  Tried a site delete command and it says my site
doesn't exist in the database. At this point I'm going to simply create a
new AWS instance and start from scratch - but this would be a nightmare on
an active server with live sites.

Have any checks been put into place to make sure wp-cli gets installed
during the updates? If that is the actual culprit?

Thanks,
Matt

**Comment by charliepryor** [comment]
I have the same issue. 

Downloading WP-CLI               [Errno 2] No such file or directory: '/usr/bin/wp'

That's the first thing that shows up upon any attempt at making a new site. I already have 5 sites created on this droplet (Ubuntu 12.04.5 Digital Ocean), but I haven't made a new site in months. Now that I try, this happens.

**Comment by dovy** [comment]
Follow all of my steps and it will work again. I had the same issue.

**Comment by charliepryor** [comment]
Just did that, installed wp-cli manually from here and it works. http://wp-cli.org 

So glad!

Now if I could figure out why my server won't update from 12.04 to 14.04 that would be even more awesome. (always errors at the end). - Would there be any advantages to updating from 12.04 to 14.04
