### ISSUE TITLE
Run HHVM in 3.0.5 version

### ISSUE THREAD

**Issue by xDae** [rtCamp/easyengine#465]
I love the update to MariaDB in this new version! But I tried to install ee engine 3.0.5 with hhvm in a fresh droplet. (https://rtcamp.com/tutorials/php/hhvm-with-fpm-fallback/)

I have installed hhvm, but when hhvm is running the database connection fail (the famous Wordpress database error connection), when I stop hhvm ```sudo service hhvm stop``` the website and database connection work fine.

Do anybody know how hhvm can run with ee engine 3.0.5 ?

**Comment by w33zy** [comment]
The issue is with HHVM 3.6.0 as per https://github.com/facebook/hhvm/issues/5002

**Comment by gau1991** [comment]
@xDae ,
The issue is not with EasyEngine. the issue is with HHVM itself.
Ref: https://github.com/facebook/hhvm/issues/5002
