### ISSUE TITLE
Move log files

### ISSUE THREAD

**Issue by benzon** [rtCamp/easyengine#467]
The current log file placement should be changed, right now if you setup virtual ftp or "Virtual" sFTP access, the costumer can not get the log files, since they are located outside the folder they got access to.

So if possible the location of log files should physically be inside /var/www/domain.com/logs

**Comment by gau1991** [comment]
@benzon ,
As per Linux directory structure standerds, all logs files must go to `/var/log/ ` folder. For our simplicity we have created its softlink to `/var/www/example.com/logs/` 
If you want to change log file location you can change that in site specifice Nginx cofiguration  using `ee site edit example.com `

> The current log file placement should be changed, right now if you setup virtual ftp or "Virtual" sFTP access, the costumer can not get the log files, since they are located outside the folder they got access to.

If you give access to your user to `/var/www/example.com/` then surely they can access log files also
