### ISSUE TITLE
ARM: Unable to run apt-get update

### ISSUE THREAD

**Issue by ViperXd** [rtCamp/easyengine#469]
Just trying new online.net ARM VPS.

So I try
```sudo ee site create example.com --wp```

But get this:
```
Adding repository for MySQL, please wait ...
Adding repository for NGINX, please wait ...
Adding repository for PHP, please wait ...
Updating apt-cache, please wait ...
Unable to run apt-get update
```
Running apt-get update by myself I get this these at the end
```
W: Failed to fetch http://mirror.aarnet.edu.au/pub/MariaDB/repo/10.0/ubuntu/dists/trusty/InRelease  
Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)


E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Assuming it might be the source of the problem.

**Comment by rippler** [comment]
It's not a bug, you're running on unsupported architecture.
See https://github.com/rtCamp/easyengine/issues/356

**Comment by gau1991** [comment]
@ViperXd ,
EasyEngine is not support for ARM vps yet. as it is dependent upon exetrenal PHP, MySQL and Nginx repo
