### ISSUE TITLE
`ee clean` command should consider pagespeed, hhvm etc

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#473]
- [ ] Make sure `ee clean --all` command clear pagespeed cache `rm -rf /var/ngx_pagespeed_cache/*`
- [ ] clean hhvm cache 
- [ ] clean memcache
- [ ] clean php zend opcache

Also add additional argas like `ee clean --pagespeed`

**Comment by harshadyeola** [comment]
@rahul286 
we don't provide `hhvm` and `pagespeed` configuration for current EasyEngine versions.
we will provide these options along with `hhvm` and `pagespeed` releases.
We have memcache and opcache clean options alredy with `ee clean` command.

**Comment by rahul286** [comment]
This is for future versions only. Also pagespeed and hhvm should be added ASAP.

**Comment by michaelryanmcneill** [comment]
Thinking about this, can you clear a remote Memcached server, or only a local one?

**Comment by willmkt** [comment]
Is pagespeed better them working only with ngix? I saw some interesting stuff in these articles and i'm willing to try.

https://danielmiessler.com/blog/ultimate-speed-wordpress-nginx/
https://danielmiessler.com/blog/nginx-caching-tempfs/

**Comment by harshadyeola** [comment]
Accomplished in EasyEngine 3.1.0.
