### ISSUE TITLE
Error - Unable to Run apt-get install

### ISSUE THREAD

**Issue by aneeshjajodia** [rtCamp/easyengine#474]
Please help.

**Comment by harshadyeola** [comment]
@aneeshjajodia 
Please try running `apt-get update` on your system.
Check if it gives any error

**Comment by aneeshjajodia** [comment]
Got the error while updating.

'W: GPG error: http://ppa.launchpad.net trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F4EA0AAE5267A6C'

**Comment by harshadyeola** [comment]
@aneeshjajodia 
Your system missing GPG keys.  
Use this command to import GPG key.
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C ` 
And use community forum for support http://community.rtcamp.com/c/easyengine

**Comment by aneeshjajodia** [comment]
I couldn't actually figure out where the prerequisite for that was written.

Also, I just wanted to ask a thing regarding the same, is easyengine a good option over manual in **installation and optimization** of wordpress on Engine X.

**Comment by harshadyeola** [comment]
@aneeshjajodia 
After adding key still you are getting problem in `apt-get install`?

**Comment by solhuebner** [comment]
This fixed the problem for me
