### ISSUE TITLE
Odd problem, not sure if it's your concern

### ISSUE THREAD

**Issue by irthos** [rtCamp/easyengine#478]
I've built a Wordpress site on mamp and a client's bluehost apache. Transferred into AWS, ran ee create, imported themes and etc all went well but a custom single-page for 'single-properties' doesn't seem to catch any css or js.

Here's the an example working on bluehost for reference:
http://vacationrentalsquebeccity.com/irthslittlecornerofsafetyamongstthemadness/vrqc/sample-resource-one/

and here's the AWS version not working:
http://aws.vacationrentalsquebeccity.com/sample-resource-one/

Sorry to add this if it's not your issue, just let me know and any advice if comes to mind. Thanks for building ee btw, really an awesome product.

**Comment by rippler** [comment]
Well, since it's working on the first site, obviously it's not an EE bug. 
Advice should be sought on the Community Forum.

**Comment by irthos** [comment]
Thanks, the first site isn't using EE. It's using traditional apache shared server setup. The AWS server is using EE and that's the one glitchin. Can you link to the Community Forum please. Thx

**Comment by rippler** [comment]
Ok, the 2nd site has a problem with (at least) JQuery and Angular.JS scripts, so a Web designer or WP guru should debug that from the browser side (since it's JavaScript). 

The URL is http://community.rtcamp.com/

**Comment by gau1991** [comment]
@irthos 
We tested it look like the problem if of JS side. You need web designer to fix this issue.
I am closing this issue now, as it is not related with EasyEngine.
For community support you can always use http://community.rtcamp.com/

**Comment by irthos** [comment]
Fair enough, thx
