### ISSUE TITLE
Unable to copy EasyEngine (ee) auto completion file

### ISSUE THREAD

**Issue by byalextran** [rtCamp/easyengine#479]
I'm getting the following error trying to upgrade EE from 2.2.1 to the latest 3.x branch. 

Here's the output from the command line. 

Any ideas on resolving the error? 

```
wget -q http://rt.cx/ee && sudo bash ee
Executing apt-get update, please wait...
Cloning EasyEngine (ee) stable branch, please wait...
Installing EasyEngine (ee), please wait...
[ Sat Mar 28 12:20:10 EDT 2015 ] Unable to copy EasyEngine (ee) auto completion file, exit status =  1
111

**Comment by gau1991** [comment]
Hi @byalextran ,
Probably its because EasyEngine not able to clone stable branch on your system, As from last few days Github is facing DDOS attacks on its servers,... 
Can you please try again to run EasyEngine install command?

**Comment by rippler** [comment]
Yeah its almost surely the DDOs thing. Try 3-4 times, it'll work.

**Comment by byalextran** [comment]
Thanks @gau1991 and @rippler. 

I tried again just now and it failed four different times. The current GitHub status on the DDoS is:

 11:50 UTC All systems reporting at 100%. Attack traffic continues, so we remain on high alert. 

I'll keep an eye on the status and try again when the attack stops.

**Comment by byalextran** [comment]
According to GitHub, everything is in the green and operating normally. However, I'm still getting the same error despite trying periodically throughout the day yesterday and today. 

Could this error be unrelated to the DDoS? 

It's a DigitalOcean server running Ubuntu 14.04. Everything has been updated using `apt-get dist-upgrade`.

**Comment by rippler** [comment]
I had a weird problem on DO just couple of days ago (see https://github.com/rtCamp/easyengine/issues/476). If this is a fresh VPS, maybe you can create a new one. Or create a new one anyway, then destroy it if it works there.
I just tried from home, the script is working fine for me.

**Comment by gau1991** [comment]
@byalextran ,
Can you give us output of following commnad?
```
tail -n50 /var/log/ee/install.log
```

**Comment by byalextran** [comment]
```
root@toad:~# wget -q http://rt.cx/ee && sudo bash ee
Executing apt-get update, please wait...
Cloning EasyEngine (ee) stable branch, please wait...
Installing EasyEngine (ee), please wait...
[ Wed Apr  1 01:16:45 EDT 2015 ] Unable to copy EasyEngine (ee) auto completion file, exit status =  1
root@toad:~# tail -n50 /var/log/ee/install.log
tail: cannot open ‘/var/log/ee/install.log’ for reading: No such file or directory
root@toad:~#
```

**Comment by gau1991** [comment]
Hi @byalextran sorry my bad,
You are updating from EasyEngine 2 to EasyEngine 3 right?
So you need to give log from EasyEngine 2 log folder

```
tail -n50 /var/log/easyengine/install.log
```

**Comment by byalextran** [comment]
aha! yup, upgrading from 2 to 3. 

```
root@toad:/var/log# tail -n50 /var/log/easyengine/install.log
graphviz					install
python-software-properties			install
software-properties-common			install
Cloning EasyEngine (ee) stable branch, please wait...
Cloning into '/tmp/easyengine'...
Installing EasyEngine (ee), please wait...
cp: cannot stat ‘/tmp/easyengine/config/bash_completion.d/ee’: No such file or directory
root@toad:/var/log#
```
in case you're wondering where the rest of the 50 lines are, i deleted them since they just repeated the section above. 

thanks for your help!
