### ISSUE TITLE
MySQLTuner Update

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#484]
Latest 1.4.0 https://raw.githubusercontent.com/major/MySQLTuner-perl/master/mysqltuner.pl 

EE has 1.1.1.

**Comment by gau1991** [comment]
We fixed this issue in EasyEngine 3.1.5, As fix was necessary because MySQLtuner installed  via apt-get causing conflict with latest version of MariaDB.
So now we installing MySQLtuner directly from Github.
