### ISSUE TITLE
Purge warning

### ISSUE THREAD

**Issue by lemartinet** [rtCamp/easyengine#485]
Hi,

I made the stupid mistake to enter
ee stack purge --all
when I meant to clean the cache for all servers

It would be great to have a warning because now I lost all my settings. Is it possible to restore them or are they gone for good? I have backups for my blogs but also stupidly no backups for my server conf. Any suggestion?

Best,
L-E

**Comment by lemartinet** [comment]
Hi!

So am I right to think that there is no way to get my config files back?

Best,
L-E

**Comment by rahul286** [comment]
@lemartinet ya. Sorry to say there is no way to get them back unless you have an external backup.

If you have few sites, may be you can run EE commands to generate config on a different server and then copy files from `/etc/`.

We already added warning as per your suggestion - https://github.com/rtCamp/easyengine/commit/9cb97cdba9324033dd7d15babef52aa162bdce66

**Comment by lemartinet** [comment]
All right, thanks for your message, and it's great that you added the warning.
Best
L-E

**Comment by rahul286** [comment]
@lemartinet Thanks for your understanding.

Sorry for inconvenience you have faced. 

If you have any more suggestions to improve EasyEngine, please let us know.
