### ISSUE TITLE
passing --php --mysql together to site create command doesn't work 

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#486]
Ran

> root@soy:~# ee site create example.com --php --mysql

Got

> Please provide valid options to creating site

--mysql implies --php but if it's explicitly stated, no error should be thrown

**Comment by harshadyeola** [comment]
@rahul286:
Here should i create site with the following order.?
If user enters explicitly  site types, create site with option which one has highest order.
1 html
2 php
3 mysql
4 wp 
5 wpsubdir/wpsubdomain

**Comment by MiteshShah** [comment]
@harshadyeola 

For --html --php then higest order is php so create php website
For --php --mysql create mysql website
For --html --mysql again create mysql website
For --html --wp create wp website
For --wp --wpsubdir create wordpress with subdir website

And so on

**Comment by harshadyeola** [comment]
@MiteshShah 
suppose user fires command `ee site create example.com --html --wpfc` then?

**Comment by MiteshShah** [comment]
@harshadyeola Then --wpfc site created
Now suppose user enter --html --php --wp --wpfc --wpsubdir then 
--wpsubdir --wpfc site should be created

@rahul286 Just confirm same you want same feature right ?

**Comment by MattyLB** [comment]
+1 ... this sounds most logical to me as a user of EE. :)

**Comment by rahul286** [comment]
Put this on hold for now. We might deprecated `--w3tc` and `--wpsc` soon.

This is a bug, but not critical. We need to address critical bugs (only) this week.
