### ISSUE TITLE
Way to exclude file from fastcgi_cache

### ISSUE THREAD

**Issue by benzon** [rtCamp/easyengine#490]
We are trying to get a Vote up down script working is there a way to bypass cache for a specific region of the site?

**Comment by rahul286** [comment]
If its a single script, you can add a `location { ` in nginx conf to bypass it.

But ideally in WordPress world, vote-up/down requests should be handled using WordPress admin ajax. EE already skips cache for WordPress admin ajax by default.

**Comment by benzon** [comment]
The issue is the vote work, but it display dos not update, it dos not show the correct number of votes.

**Comment by rahul286** [comment]
All such counts should be fected via (admin) ajax. If it's added to page during page-generation, it will be cached. 

Also, please use http://community.rtcamp.com/c/easyengine for support.
