### ISSUE TITLE
When upgrading to hhvm there is a problem with database backup

### ISSUE THREAD

**Issue by yustein** [rtCamp/easyengine#496]
Here is the error I get and to be clear, I'm not using a local database but Amazon RDS so I don't even need a backup of the local database...

I would appreciate any help because I want to test hhvm
```
2015-04-16 14:29:01,539 (INFO) ee : Backing up database
2015-04-16 14:29:01,539 (DEBUG) ee : Running command: mysqldump deleted > /var/www/thisismydomainIdeleteditforprivacy/backup/16Apr2015142858/deleted.sql
2015-04-16 14:29:01,545 (DEBUG) ee : Command Output: ,
Command Error: mysqldump: Got error: 1049: "Unknown database 'deleted'" when selecting the database

2015-04-16 14:29:01,545 (INFO) ee : [Fail]
2015-04-16 14:29:01,545 (DEBUG) ee : 'mysqldump failed to backup database'
2015-04-16 14:29:01,545 (ERROR) ee : Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
```

**Comment by harshadyeola** [comment]
@yustein
We have tested with RDS, We have not faced any issues with RDS 
 
> 2015-04-16 14:29:01,539 (DEBUG) ee : Running command: mysqldump deleted > /var/www/thisismydomainIdeleteditforprivacy/backup/16Apr2015142858/deleted.sql
2015-04-16 14:29:01,545 (DEBUG) ee : Command Output: ,
Command Error: mysqldump: Got error: 1049: "Unknown database 'deleted'" when selecting the database

It seems that your database is marked as deleted in `ee database`.  
Can you please crosscheck it with `ee site info yourdomain.com`?

**Comment by yustein** [comment]
Here it is, maybe since I moved to RDS?

```
Nginx configuration      wp wpfc (enabled)
Pagespeed                disabled
HHVM                     disabled
access_log               /var/www/xxxxxxxxxxxxxx/logs/access.log
error_log                /var/www/xxxxxxxxxxxx/logs/error.log
Webroot                  /var/www/xxxxxxxxxx
DB_NAME                  deleted
DB_USER                  deleted
DB_PASS                  deleted
```

**Comment by gau1991** [comment]
Hi @yustein ,
From your site info it looks like you have deleted the db. EasyEngine is not supposed to take backup of deleted db. So I am marking this as bug.

**Comment by yustein** [comment]
Thanks. Interesting thing is I did a ```ee update``` and now it works. For some reason it couldn't find the database before this. 

Then I got a white screen so I had to disable the plugins and reenable them one by one. But the speed is phenomenal, this is the NEW PHP for sure!

**Comment by harshadyeola** [comment]
@yustein 
Glad to know your problem got fixed.

**Comment by yustein** [comment]
Is there a way to install ee with the default system ip?

**Comment by encodia** [comment]
Hello,

we are getting the same error here:

2015-07-10 09:45:34,858 (INFO) ee : Backup location : /var/www/xxxxxx.com/backup/10Jul2015094524
2015-07-10 09:45:34,858 (DEBUG) ee : Copying file, Source:/etc/nginx/sites-available/xxxxxx.com, Dest:/var/www/xxxxxx.com/backup/10Jul2015094524
2015-07-10 09:45:34,859 (INFO) ee : Backing up database
2015-07-10 09:45:34,859 (DEBUG) ee : Running command: mysqldump xxxxxx_com > /var/www/xxxxxx.com/backup/10Jul2015094524/xxxxxx.sql
2015-07-10 09:45:34,877 (DEBUG) ee : Command Output: ,
Command Error: mysqldump: Got error: 1045: "Access denied for user 'root'@'localhost' (using password: YES)" when trying to connect

May u have any idea to solve it? I am trying to update with hhvm...

Thank you!

**Comment by iam404** [comment]
Hello @encodia 

There seems to be a misconfiguration in your ` .my.cnf` file .
Please verify your mysql credential using
`cat  ~/.my.cnf`

**Comment by puccaso** [comment]
i'm having the same issue


Nginx configuration	 wp wpfc (enabled) 
PHP Version		 7.0
HHVM			 enabled
SSL			 enabled
SSL PROVIDER             Lets Encrypt
SSL EXPIRY DATE          Wed May 29 08:37:53 EDT 2019

access_log		 /xxxxxxxx/mahirsayar.com/logs/access.log
error_log		 /xxxxxxxx/mahirsayar.com/logs/error.log
Webroot			 /xxxxxxxx/mahirsayar.com
DB_NAME			 deleted
DB_USER			 deleted
DB_PASS			 deleted

i can see all the correct info in my wp-config.php - and the site works fine, 
but i can't upgrade because i cant seem to get ee to accept whats actually there..
