### ISSUE TITLE
sftp with password is failing 

### ISSUE THREAD

**Issue by shaneholloman** [rtCamp/easyengine#501]
```
root@ee:~# passwd www-data
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully
root@ee:~# exit
logout
Connection to 104.131.175.19 closed.

shane at rocket in ~
$ sftp www-data@104.131.175.19
www-data@104.131.175.19's password:
Received message too long 141612888
```

**Comment by harshadyeola** [comment]
@shaneholloman 

This may be due to welcome message after successfull ssh login. SFTP doesnot like welcome message.
Please comment out welcome messages in your `.bashrc` or  profile.

**Comment by harshadyeola** [comment]
@shaneholloman 
I guess this problem does not occur with ssh login to www-data user. 
I am closing this issue as it is related to SFTP problem.
