### ISSUE TITLE
NGINX fails to reload after adding ---hhvm

### ISSUE THREAD

**Issue by ddelaey** [rtCamp/easyengine#504]
Debian7, 1GB VPS, EE3.1.1

root@vm1855:~# ee site update mysite.com --hhvm
Adding repository for NGINX, please wait ...
Adding repository for HHVM, please wait ...
Updating apt-cache, please wait ...
Installing packages, please wait ...
Reload : nginx     [Failed]
Restart : hhvm      [OK]
Running pre-update checks, please wait ...
NGINX configuration check failed.

What can be wrong?

**Comment by ddelaey** [comment]
It seems there are a few issues:

First:
When looking at '/etc/nginx/nginx.conf' there are multiple lines containing 'worker_rlimit_nofile 100000;', which cause nginx failing to restart.

Howcome 'worker_rlimit_nofile 100000;' is multiple times in there? What can be the cause?

user www-data;
worker_processes auto;
worker_rlimit_nofile 100000;
worker_rlimit_nofile 100000;

events {
    worker_connections 4096;
    multi_accept on;
}
worker_rlimit_nofile 100000;
pid /run/nginx.pid;

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 30;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    gzip on;
    gzip_disable "msie6";
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}


Second:
My site uses SSL and has a modified config file (ee site edit mysite.com).
After adding --hhvm and/or --pagespeed, my configuration is replaced with a default configuration, causing mysite.com not loading anymore.

How can this overwrite of the config file be prevented?

root@vm1855:~# ee site update mysite.com --hhvm=on
Running pre-update checks, please wait ...
Backup location : /var/www/mysite.com/backup/22Apr2015194538
Backing up database 		[Done]
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Reload : nginx     [OK]
Successfully updated site http://mysite.com
root@vm1855:~# ee site update mysite.com --pagespeed=on
Running pre-update checks, please wait ...
Backup location : /var/www/mysite.com/backup/22Apr2015194558
Backing up database 		[Done]
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Reload : nginx     [OK]
Successfully updated site http://mysite.com

**Comment by gau1991** [comment]
HI @ddelaey ,
> How can this overwrite of the config file be prevented?
We are working on this. It will take some time to come up with alternative solution for this.

> Running pre-update checks, please wait ...
NGINX configuration check failed.
> What can be wrong?

I am not able to see this issue on Fresh Debian 7. I am closing this issue now. Reopen this issue if see this message again during site creation.
