### ISSUE TITLE
Clarification: How to dev a site before pointing the domain to it

### ISSUE THREAD

**Issue by irthos** [rtCamp/easyengine#511]
Hi, forgive me if I overlooked this answer in the docs. I'm using EC2 and want to develop a site before redirecting the dns making it live. I've tried the obvious 54.201.121.102/aws.deluxepleasure.com (aws.deluxepleasure.com is the created site).

Aside from dealing with wp-options site_url etc what do I need to do to get the site up via direct ip or the ec2 public dns?

Thank you very much!

**Comment by bml13** [comment]
You can configure the the site in the new server with the normal url: deluxepleasure.com
Then in your local machine edit your /etc/hosts file and add the line
             deluxepleasure.com      ip-of-new-server
like that your browser will use the ip-of-new-server for that domain, it takes it from hosts instead of public dns.

**Comment by rahul286** [comment]
@irthos our current method is as @bml13 had suggested above when developing locally.

For staging site, we as of now create a replica site like `staging.example.com` and use wp-cli to search-replace database entries. We have plan to add this in EE as `ee site clone` command in feature.

**Comment by irthos** [comment]
I appreciate the how fast you both helped on this! i think this would be better handled on the new server because . for example, we might need to show others the work before we have a domain or during dns changes. also, i think it could become problematic to manage the hosts file over time as i.p.'s might change, too. 

My wish would be for the folder to be included in the main nginx conf on `ee site create example.com` so that we can navigate to the app immediately. I guess the challenge with wordpress would be confusing the site urls in sql but it sounds like the `ee site clone` command sounds likea useful utility.

Please let me know if I should close this issue, change it to a feature request, or just deal :P

Thanks much!

**Comment by irthos** [comment]
btw, no success yet but I created a symlink inside of the etc/www/html folder could be an easy way but getting 403 from nginx. not sure about the right way to use `disable_symlinks` or is there something much simpler? i've also tried to set the conf root to reflect the symlink and restarted the server but continues to get 403 when i navigate to 54.201.121.102/aws.deluxepleasure.com

**Comment by aportbury** [comment]
Hey @irthos this is how we run ours. 

We edit our DNS to setup a cname record with a subdomain pointing to our primary domain:
```bash
CNAME - newsite.com.primarysite.com - primarysite.com 
```
Then using ee site edit newsite.com we add the subdomain to the list: 

```bash
server_name primarysite.com www.primarysite.com newsite.com.primarysite.com
```

Upon save, ee will automatically restart nginx. 

Then you are able to access the site via the subdomain: newsite.com.primarysite.com

When you're ready to go live, simply use wp-cli to run a search and replace: 

```bash
wp search-replace 'http://newsite.com.primarysite.com' 'http://realdomain.com'
```

**Comment by irthos** [comment]
Thanks for the help! this isn't optimal for this feature request Because it necessitates having a domain and extra steps to track. I'm hoping to dev on the live aws server via the ip or public domain immediately after creating the instance and running ee site create.. before a domain is connected. Cheers on the insight, it will prove useful in other cases!

**Comment by aportbury** [comment]
You could still use the above scenario then, just using an A record instead of an CNAME. This way you can point the subdomain directly at the AWS IP address.

**Comment by irazasyed** [comment]
@irthos Why don't you consider using programs like [ngrok](https://ngrok.com/)? It gets the job done. We use it on every project. It basically lets outsider connect and check the project remotely. You have to keep the connection open though, So it's good if the project discussion is going on with the client and or with the team and close when done reviewing.

**Comment by irthos** [comment]
@aportbury thanks, this still involves using a domain which shouldn't be necessary, imo. 
@irazasyed that's a decent workaround to get the effect. I'll close this issue but if anyone else thinks `ee site create` should also create a live dev folder, make a feature request.

For reference, godaddy's managed wordpress creates a dummy url that later integrates with any domain by A-record. It was nice to dev on the live server without worry of superfluous commands. I imagine there's more to it than setting a fresh nginx.conf but I'm not that familiar with how EE works under the hood yet.

Cheers all!
