### ISSUE TITLE
DNS Records

### ISSUE THREAD

**Issue by sianios** [rtCamp/easyengine#513]
Well, after I suggested the project to a friend of mine he asked me, what should I do now with the DNS records? My suggestion is after you install for example a mailserver to echo the DNS records you need add to the DNS.
Thank you.

**Comment by harshadyeola** [comment]
@sianios 

Well your frient can update entry in `/etc/hosts/` .

Please use community forum for support  (http://community.rtcamp.com/c/easyengine).
I am closing this ticket for now. Feel free to create ticket on community forum if you face any problems with EasyEngine.
