### ISSUE TITLE
PageSpeed being shut down - alternatives?

### ISSUE THREAD

**Issue by joeguilmette** [rtCamp/easyengine#534]
https://developers.google.com/speed/pagespeed/service/Deprecation

**Comment by deprito** [comment]
Hmm, i'm little bit confused.

Whats the differrent, between pagespeed service & pagespeed technology (apache
mod, etc)?





Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.3.14&pv=5.1.1]

On Thu, May 07, 2015 at 3:49 PM, joeguilmette < notifications@github.com [notifications@github.com] > wrote:
https://developers.google.com/speed/pagespeed/service/Deprecation
[https://developers.google.com/speed/pagespeed/service/Deprecation]

**Comment by MiteshShah** [comment]
@joeguilmette  I guess its just Google PageSpeed service shutdown not the pagespeed development.

Just to confirm same created issue on official ngx_pagespeed channel
Rfer: https://github.com/pagespeed/ngx_pagespeed/issues/964

**Comment by MattyLB** [comment]
This doesn't affect server side pagespeed packages or the open source
repositories, just google's own hosted service. Though it does pose
questions on who will maintain the open source packages.

**Comment by MiteshShah** [comment]
@deprito

Google PageSeed service is paid service you just have to make some changes on DNS and you are ready to go.

Apache mod_pageseed and ngx_pagespeed you have to manually compile and install pagespeed module on your server.

**Comment by gau1991** [comment]
@joeguilmette ,
The article is taking about PageSpeed service that Google provides for site optimization. We are using plugin which is also called as Ngx_pagespeed.

Please for following section in that artical:
```
Alternatives to PageSpeed Service

If you wish to continue enjoying many of the performance benefits of PageSpeed Service, the same Google PageSpeed technology is available in a number of alternative packagings which you may wish to consider using. These alternatives are not affected by the deprecation announcement and continue to be supported.
Provider Hosted PageSpeed

Many web hosting providers already integrate PageSpeed. If you are using such a web hosting provider, check your provider’s documentation. It may be as simple as checking a box in your provider’s control panel.
Server side modules

There are PageSpeed modules for many common web servers. If you run your own web server, you may wish to install one of these.
Apache

Google has developed the open-source Apache module mod_pagespeed. Pre-built binary modules for Apache 2.2 and 2.4 are available. For more information, click here.
Nginx

Google has also developed a plugin for Nginx. Due to the nature of Nginx, it must be compiled from source. You can read the instructions here. 
```

**Comment by jeffkaufman** [comment]
> Though it does pose questions on who will maintain the open source packages.

The open source packages are still under active development by the same team of Google employees and external contributors that's been working on them all along.
