### ISSUE TITLE
Duplicate ssl_prefer_server_ciphers directive

### ISSUE THREAD

**Issue by remoteur** [rtCamp/easyengine#539]
Hi all,

On a fresh install (on Debian Wheezy) 'ee site create example.com --wpfc' results in nginx failing to reload with the following error message:

nginx: [emerg] "ssl_prefer_server_ciphers" directive is duplicate in /etc/nginx/conf.d/ee-nginx.conf:24

ssl_prefer_server_ciphers is also placed in nginx.conf

**Comment by gau1991** [comment]
Hi,
The issue was caused because of changes in Nginx config in latest Nginx version.
We now fixed this issue in EasyEngine 3.1.5

**Comment by harshadyeola** [comment]
@remoteur 
EasyEngine 3.2.0 has its own nginx packages build with openSUSE Build Service.
So there will be no more conflicts in configuration. check that out and update your server for latest EasyEngine.
