### ISSUE TITLE
404 error after running ee site create

### ISSUE THREAD

**Issue by remoteur** [rtCamp/easyengine#540]
Running 'ee site create example.com --wpfc' results in a 404 File Not Found page for the example.com domain. Running ee v3.1.4 on Debian Wheezy.

**Comment by maxsinus** [comment]
Yes, it happening when using Debian and nginx 1.8, I suggest you to read this thread https://github.com/rtCamp/easyengine/issues/538

**Comment by harshadyeola** [comment]
@remoteur @maxsinus 
Check this for solution
https://github.com/rtCamp/easyengine/issues/538#issuecomment-101635369

**Comment by gau1991** [comment]
@remoteur ,
We fixed this issue in EasyEngine 3.1.5
