### ISSUE TITLE
Pretty Pissed - Upgrade does 502/504 bad gateway

### ISSUE THREAD

**Issue by dovy** [rtCamp/easyengine#541]
Debian 7, fresh server. Installed on 3 different boxes! Having an issue with your php5-fpm going to a bad gateway. No matter what I do.

I need this resolved. You've brought my entire site down. I may have to leave EE completely.  :(

**Comment by wolerine** [comment]
I had the same problem. If is that possible just try to install Ubuntu 14.04. It solved my problem.

**Comment by dovy** [comment]
Seems like it was a conflict with old EE code and a corrupt update. Oy.

**Comment by joeguilmette** [comment]
If you ever need support they offer premium support via rtcamp. I don't
think it's fair to demand that level of support in a GitHub issue.

**Comment by dovy** [comment]
Sorry, I was up till 4am and someone else solved it.

It just seems lately the new ee versions have been corrupting things. You're right, I shouldn't have been so harsh, but I was getting quite the support emails  

Please make updates work. ;)

**Comment by MattyLB** [comment]
Dovy,

I agree it can be frustrating at times but we're all here to help make this
awesome tool better.  You mentioned support emails... Are you blindly
updating live sites/servers??  Create a dev Image and try things out there
first. This thread is for improving EE. :)

**Comment by harshadyeola** [comment]
@dovy 
> it was a conflict with old EE code and a corrupt update.
can you tell me what was the problem and how you did solve it?
