### ISSUE TITLE
ee stack upgrade - not detecting mysql

### ISSUE THREAD

**Issue by rippler** [rtCamp/easyengine#544]
This is with the current version:
root@www:~# ee  -v
EasyEngine v3.1.4
Copyright (c) 2015 rtCamp Solutions Pvt. Ltd.

I have 2 WP sites and then when I run stack upgrade, it claims MySQL is not installed.

```
root@www:~# ee stack upgrade
During package update process non nginx-cached parts of your site may remain down
Do you want to continue:[y/N]y
HHVM is not installed
MySQL is not installed
Updating packages, please wait...
Successfully updated packages
You have new mail in /var/mail/root
```

After that, the sites are working normally and services are shown as detected.

```
root@www:~# ee stack status
nginx     :  Running
php5-fpm  :  Running
mysql     :  Running
postfix   :  Running
```

I had the same experience on another system (where for example nginx was v1.6 and I wanted to upgrade it to v.1.8). It worked, but I find it strange that MySQL was shown as not installed (is it because we changed from Percona or something?). I installed this stack with EE v2.x and didn't touch it since then.

**Comment by gau1991** [comment]
Hello @rippler ,
Currently `ee stack upgrade` upgrades only MariaDB, as with latest EasyEngine we only supports MariaDB.
The message on screen was creating confusion, so we updated message to `MariaDB is not installed` in latest EasyEngine.
