### ISSUE TITLE
Duplicated "ssl_prefer_server_ciphers"

### ISSUE THREAD

**Issue by charliehu** [rtCamp/easyengine#546]
Hello,

On Debian 7, both /etc/nginx/nginx.conf and /etc/nginx/conf.d/ee-nginx.conf file contains  "ssl_prefer_server_ciphers" directive.

**Comment by irazasyed** [comment]
It seems like it has already been reported here: #539 Should consider following that and probably close this.

**Comment by gau1991** [comment]
Hi,
We fixed in EasyEngine 3.1.5

**Comment by harshadyeola** [comment]
@irazasyed @charliehu 
EasyEngine 3.2.0 has its own nginx packages build with openSUSE Build Service.
So there will be no more conflicts in configuration. check that out and update your server for latest EasyEngine.
