### ISSUE TITLE
Error writing ee.conf

### ISSUE THREAD

**Issue by dtdw** [rtCamp/easyengine#548]
I forgot my wordpress pw, and also the email.

Tried editing it, but it kept throwing errors refusing to save the file in ee.conf (plus it's blank)

Where does it keep my user name pass? Now I am completely locked out.

http://prntscr.com/76kklq

**Comment by harshadyeola** [comment]
@dtdw 
Please use http://community.rtcamp.com/c/easyengine for the support requests.
BTW you are editing confing at wrong location. EasyEngine configuration file path is `/etc/ee/ee.conf`
I am closing this ticket and if you have any doubts please raise ticket at community forum first.

**Comment by dtdw** [comment]
Hey,

Thanks, that works. 

The problem was because I followed the faq at the site, and the file path is
/etc/easyengine/ee.conf

https://rtcamp.com/easyengine/faq/#ee18
