### ISSUE TITLE
fastcgi_cache ningx push module error in logs

### ISSUE THREAD

**Issue by htpcBeginner** [rtCamp/easyengine#554]
I am seeing a lot of these errors in the logs:

[info] 15722#0: Using 32KiB of shared memory for push module in /etc/nginx/nginx.conf:137

Digging a bit, there is a bug that was fixed: https://bugs.launchpad.net/nginx/+bug/1216817

I have not seen the fix through rtcamp's nginx repository. How can I apply the fix?

**Comment by harshadyeola** [comment]
@htpcBeginner 

I guess this problem of your have been fixed when you updated to EasyEngine latest version as it installs package from its own repo.

I am closing this issue for now.
