### ISSUE TITLE
I can't login as admin user after site create.

### ISSUE THREAD

**Issue by crapthings** [rtCamp/easyengine#557]
wp shows

    ERROR: Invalid username. Lost your password?

    sudo ee site create test.com --wp

it shows successfully created site http://test.com
and with admin user and admin random password.

But it just can't login with that user and password.

**Comment by harshadyeola** [comment]
@crapthings 
 Please create ticket on cummunity forum (community.rtcamp.com/c/easyengine). We can provide you support there.
