### ISSUE TITLE
Add Let's Encrypt support to EasyEngine roadmap

### ISSUE THREAD

**Issue by jnimmo** [rtCamp/easyengine#559]
Let's Encrypt is a free, automated and open certificate authority, launching mid 2015. This provides anyone with a way of offering HTTPS at no extra cost.

A Python client will:
- Automatically prove to the Let’s Encrypt CA that you control the website
- Obtain a browser-trusted certificate and set it up on your web server
- Keep track of when your certificate is going to expire, and automatically renew it
- Help you revoke the certificate if that ever becomes necessary.

The client software already works with Nginx, but wouldn't it be cool if EasyEngine users could just add a '--letsencrypt' arg when creating a site and have a trusted SSL cert automatically installed and managed for free

**Comment by xkidro** [comment]
This is a pretty awesome idea / feature.

**Comment by xkidro** [comment]
This is a pretty awesome idea/feature for EasyEngine. 
+1

**Comment by MiteshShah** [comment]
@jnimmo Sound good to me :)
Easy to use also https://letsencrypt.org/howitworks/

**Comment by rahul286** [comment]
It's already on roadmap - https://github.com/rtCamp/easyengine/issues/376

**Comment by jnimmo** [comment]
Thanks and sorry all - hard tried searching but couldn't find

**Comment by rahul286** [comment]
No problem. Github search is very poor. Even I couldn't find it via search.

I have plans for this since the day this initiative was launched. :-)

I thank you for adding details. If there is any tutorial which we can refer to, it will speed up things.

**Comment by MattyLB** [comment]
wow, huge +1 here! :)
