### ISSUE TITLE
Pagespeed conf should be delayed

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#562]
`/etc/nginx/conf.d/pagespeed.conf` is added by default.

pagespeed is conflicting with lua module which is a really serious conflict.

In any case, no traces of experimental feature should be present unless they are used somewhere.

On this particular site, I did not use pagespeed at all so it took time to guess lua code not working because of pagespeed :(

**Comment by MiteshShah** [comment]
> In any case, no traces of experimental feature should be present unless they are used somewhere.

By default nginx.conf include any file present inside /conf.d/*
```
include /etc/nginx/conf.d/*.conf;
```
Need to move pagespeeed file from conf.d to common directory and have to test it.

**Comment by rahul286** [comment]
Related to #564
