### ISSUE TITLE
Files downloaded as .php

### ISSUE THREAD

**Issue by timersys** [rtCamp/easyengine#563]
Hi my files are being downloaded as .php instead or index.zip on some cases instead of the correct names.

Any clue on what can be happening?

The urls are lie https://xxxxx.com/index.php?eddfile=xxxxx&ttl=1433874397&file=0&token=xxxx and

**Comment by bigwilliam** [comment]
Please use the support forums for support requests: http://community.rtcamp.com/c/easyengine

**Comment by harshadyeola** [comment]
@timersys 

Lets discuss this on community forum (http://community.rtcamp.com/c/easyengine). As this problem is with you only, we will try to find solution and if it comes up with update in EasyEngine will reopen this thread.

Thanks
