### ISSUE TITLE
Improving experimental feature handling

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#564]
- [x] `ee stack` switches for dependency management e.g. `ee stack install --hhvm`, `ee stack install --pagespeed`
- [x] Delayed dependency installation. e.g. do not install hhvm till `ee site create example.com --hhvm` is called.
- [x] A clear warning and prompt e.g "HHVM is experimental feature and it may not work with all plugins all your site. You can disable it by passing `hhvm=off` later. Do you wish to enable HHVM now for example.com? Type "yes" to continue. [no] __". This prompt can be skipped by adding `--experimental` flag to original command. 

Ref: http://community.rtcamp.com/t/installation-process-for-hhvm-fails-causing-ee-installation-to-halt/4605

**Comment by gau1991** [comment]
Fixed in EasyEngine 3.2.1
