### ISSUE TITLE
Packages cannot be authenticated

### ISSUE THREAD

**Issue by sianios** [rtCamp/easyengine#566]
On a fresh Ubuntu 14.04 LTS vagrant environment I am trying to install the web packages with ```sudo ee stack install --web``` or with ```sudo ee stack install --all``` and always get an error. ```sudo tail /var/log/ee/ee.log``` gives me the following:

vagrant@trusty64:~$ sudo tail /var/log/ee/ee.log
0 upgraded, 198 newly installed, 0 to remove and 4 not upgraded.
Need to get 85.5 MB of archives.
After this operation, 357 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  mysql-common mariadb-common libmariadbclient18 libmysqlclient18
  mariadb-client-core-10.0 mariadb-client-10.0 mariadb-server-core-10.0
  mariadb-server-10.0 hhvm mariadb-server nginx-common nginx-custom
E: There are problems and -y was used without --force-yes
2015-06-15 07:00:11,906 (INFO) ee : Oops Something went wrong!!
2015-06-15 07:00:11,906 (ERROR) ee : Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

ee version:
vagrant@trusty64:~$ sudo ee -v
EasyEngine v3.2.0
Copyright (c) 2015 rtCamp Solutions Pvt. Ltd.

**Comment by gau1991** [comment]
Related to #560.
@sianios , refer: https://github.com/rtCamp/easyengine/issues/560#issuecomment-110263534
