### ISSUE TITLE
HHVM Error: (111: Connection refused)

### ISSUE THREAD

**Issue by JosefJezek** [rtCamp/easyengine#567]
`2015/06/16 15:44:21 [error] 1650#0: *38787 connect() failed (111: Connection refused) while connecting to upstream, client: 178.17.6.166, server: test.com, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:8000", host: "test.com", referrer: "http://test.com/wp-admin/"`

Solution is `hhvm.server.ip = 127.0.0.1`

http://stackoverflow.com/questions/27137094/hhvm-nginx-connection-refused

**Comment by gau1991** [comment]
Hi @JosefJezek ,
On which OS you faced this issue?
Can you give me bit more details?
```
hhvm --version
lsb_release -a
```

**Comment by JosefJezek** [comment]
HipHop VM 3.7.1 (rel)
Description:    Ubuntu 14.04.2 LTS

**Comment by JosefJezek** [comment]
Thank you
