### ISSUE TITLE
Database appears deleted

### ISSUE THREAD

**Issue by allgameplaya** [rtCamp/easyengine#575]
I have a working site with EasyEngine. However, when I try to update the cache to W3TC and run:

`eesite  update xxxa.com --w3tc `

    Running pre-update checks, please wait...
    Backup location : /var/www/xxxa.com/backup/03Jul2015120644
    Backing up database             [Fail]
    Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

This is what the log says:
`Command Error: mysqldump: Got error: 1049: "Unknown database 'deleted'" when selecting the database`

It turns out that the database appears as deleted when it's actually not. When i run ee site info, this is what I see:

`ee site info xxxa.com`

    Nginx configuration      wp wpsc (enabled)
    Pagespeed                disabled
    HHVM                     disabled
    access_log               /var/www/xxxa.com/logs/access.log
    error_log                /var/www/xxxa.com/logs/error.log
    Webroot                  /var/www/xxxa.com
    DB_NAME                  deleted
    DB_USER                  deleted
    DB_PASS                  deleted

How can I update the database information? It's certainly not deleted.

Thank you in advance for your help!

**Comment by allgameplaya** [comment]
SOLVED!!

It seems like easyengine deletes the database and there is no way to recreate without manually editing the database found at:

`/var/lib/ee/ee.db`

(You will need a program such as SQLBrowser). After updating the file with database details, I was able to upgrade without a problem.

**Comment by harshadyeola** [comment]
@allgameplaya 
EasyEngine keeps site entry in sync in its  database. if you have moved your wp-config.php or if it does not find that at specific location it marks database as deleted in its database.

We will be updating search location for wp-config.php one more level i.e inside htdocs/ .
