### ISSUE TITLE
can't login to mysql

### ISSUE THREAD

**Issue by danecando** [rtCamp/easyengine#577]
I've updated the password in the .my.cnf file but it doesn't seem to take. i've tried reloading the stack restarting mysql and everything else that I can think of and it still won't let me login with the credentials in .my.ncf

**Comment by andrewklimek** [comment]
That file doesn't set your password, that's just a reference for ee to log you in automatically.  You'll have to change the password from MySQL but since you changed that file ee may not be able to log you in.

**Comment by bigwilliam** [comment]
@danecando, please post your support questions at the community forum here: http://community.rtcamp.com/

This page is for discussions about the development of EE.
