### ISSUE TITLE
(Atomic deployments) Symlinked website root directory issue

### ISSUE THREAD

**Issue by ynt** [rtCamp/easyengine#579]
I'm trying to set up atomic deployment for website on EasyEngine powered Ubuntu server. Unfortunately, PHP scripts do not work if website root directory is a symlink.

Will EE support atomic deployments?

**Comment by bigwilliam** [comment]
Please direct your support questions to http://community.rtcamp.com

**Comment by ynt** [comment]
Everything works fine. I made a mistake.
