### ISSUE TITLE
Infected server 

### ISSUE THREAD

**Issue by willmkt** [rtCamp/easyengine#584]
Hello,

I really need help!

My server on digital ocean has infected, I see a lot of connections, but i don't know which are infected.

here is a part of the connections:

http://tinypic.com/r/2djtr29/8

Can someone help me find a solution?

Thanks.

**Comment by benzon** [comment]
Looks like a socket leak rather then infection....

**Comment by harshadyeola** [comment]
@willmkt 

Please use community forum for discussion.
