### ISSUE TITLE
Is there a possibility to support other OSes, like FreeBSD?

### ISSUE THREAD

**Issue by csfalcao** [rtCamp/easyengine#592]
Is there a possibility to support other OSes, like FreeBSD?

**Comment by nivit** [comment]
+1

**Comment by rjdp** [comment]
no plans currently though we too definitely wud love  to see it run on many other OSes .

**Comment by csfalcao** [comment]
My question comes from this excellent article (https://www.nginx.com/blog/thread-pools-boost-performance-9x/) and is related about **thread pools**, a feature that in a specific scene can increase Nginx's performance in 900%!

This feature is no present in any Linux Distro:
*"The culprit is that operating systems are missing this feature. The first attempts to add it to Linux as the fincore() syscall were in 2010 but that didn’t happen. Later there were a number of attempts to implement it as a new preadv2() syscall with the RWF_NONBLOCK flag (see Non-blocking buffered file read operations and Asynchronous buffered read operations at LWN.net for details). The fate of all these patches is still unclear. The sad point here is that it seems the main reason why these patches haven’t been accepted yet to the kernel is continuous bike shedding."*

After that, the article reveals that this feature is **native** in FreeBSD:
*"On the other hand, users of FreeBSD don’t need to worry at all. FreeBSD already has a sufficiently good asynchronous interface for reading files, which you should use instead of thread pools."*

The article also explains a workaround method to *kinda* get this in Linux.

I've always used Ubuntu, but after this article I started to get a real interest in FreeBSD.

**Comment by rjdp** [comment]
Thanks for your amazing info. sure will speculate on your suggestion . Have tried the work around in ubuntu

**Comment by iam404** [comment]
Hello @csfalcao 

Please use our community support forum for any query related issues  http://community.rtcamp.com/c/easyengine . I am closing this issue for now .
