### ISSUE TITLE
Enabling redis on more than one site messes up the sites.

### ISSUE THREAD

**Issue by ddelaey** [rtCamp/easyengine#593]
Enabling redis on more than one site messes up the sites.

I've installed ee 3.3.1 on a fresh Debian 8.1 VPS.
Next I've created 4 sites on that VPS:
```
ee site create mysite1.com --wpredis
ee site create mysite2.com --wpredis
ee site create mysite3.com --wpredis
ee site create mysite4.com --wpredis
```

Next I log in on all the 4 sites and I enable the "redis object cache" on the first site.
As soon as I enable the "redis object cache" on the second site, I get logged of that second site and it is not available anymore. When going to 'mysite2.com' it redirects to 'mysite1.com'.
The same happens for the third and the fourth site as soon as I enable the "redis object cache".

Note that I started from a fresh Debian 8.1 VPS.

This is a major issue with the redis cache.

How to fix this?

Trying to disable redis is not successful.
```
ee site update mysite1.com --wp
ee site update mysite2.com --wp
ee site update mysite3.com --wp
ee site update mysite4.com --wp
ee clean --all
```

**Comment by rjdp** [comment]
@ddelaey , please post your support questions at the community forum here: http://community.rtcamp.com/
This page is for discussions about the development of EE.

**Comment by ddelaey** [comment]
@rjdp 
This is not just a question, it's reporting a bug in EE!
Correct me if I'm wrong but bugs are supposed to be reported here I guess?

**Comment by bigwilliam** [comment]
@ddelaey you should confirm it is a bug with the community before opening an issue here. Many times people post here with issues that end up not being a bug in EE.

**Comment by ddelaey** [comment]
@bigwilliam

From the description I made It is pretty clear this is a bug don't you think.

**Comment by bigwilliam** [comment]
@ddelaey Sorry but it was not clear. All too often people post here with community questions. You posted a question: "How do I fix this?" and you didn't "report" log files or evidence. In my opinion this looks like a community post. 

Albeit you are right, there must be a bug here. I duplicated what you did (on Ubuntu), and I can confirm that this is happening.

**Comment by ddelaey** [comment]
See also the discussion at: http://community.rtcamp.com/t/enabling-redis-on-more-than-one-site-messes-up-the-sites/4893

Anyway, I think it's also a matter of having clear and detailed documentation. Plus EE should be able to handle this automatically without any manual editing IMO.

Can the EE engineers comment on this please?

**Comment by rahul286** [comment]
Yep. This is something we should have handled on our end.

We will release a patch soon. Patch will do same thing as discussed in community thread:

```define( 'WP_CACHE_KEY_SALT', 'sitename:' );```

It will add `sitename` specified to `ee site create` command as cache key salt.

We hope to release fix tomorrow by this time.

Sorry everyone for inconvenience.

**Comment by ddelaey** [comment]
@rahul286 Thanks for picking this up :-)

**Comment by ddelaey** [comment]
@Prabuddha @harshadyeola

I've updated to V3.3.2 and I get following issue:
    
    /home/david# ee -v
    EasyEngine v3.3.2
    Copyright (c) 2015 rtCamp Solutions Pvt. Ltd. 

    /home/david# ee site create myothersite.com --wpredis
    Redis is experimental feature and it may not work with all CSS/JS/Cache of your site.
    You can disable it by changing cache later.
    Do you wish to enable Redis now for myothersite.com?
    Type "y" to continue [n]:y
    Unable to Search string SCRIPT_FILENAME in /etc/nginx/fastcgi_params

What's happening?

Kind regards,
  David

**Comment by rjdp** [comment]
@ddelaey  , looks like `/etc/nginx/fastcgi_params` is missing in your nginx installation , try placing a generic fastcgi_params file at  `/etc/nginx/` like the one at [here](http://wiki.nginx.org/PHPFcgiExample) , if this doesn't Fixes it , plz  continue this discussion at [rtcamp community forum] (community.rtcamp.com)

**Comment by ddelaey** [comment]
The ```fastcgi_params ``` file was renamed to ```fastcgi_params.old ```, but no new ```fastcgi_params ``` file was created.
The ```nginx.conf ``` file was renamed to ```nginx.conf.old ```, but no new ```nginx.conf `` file was created.
The only thing I did was ``` ee update ``` and ```ee site create ```, nothing else.
Can this be an issue/bug in ee?

**Comment by harshadyeola** [comment]
@ddelaey 
>The fastcgi_params file was renamed to fastcgi_params.old, but no new fastcgi_params file was created.
have you renamed this file by yourself? It is installed when `nginx-custom` package is installed in your system.
Is there any reason you have renamed this file?

**Comment by ddelaey** [comment]
@harshadyeola 

I did not create the .old files myself.
When doing an ```ls -l ``` at ```/etc/nginx ``` I saw that ```fastcgi_params ``` and ```ngnix.conf ``` file were not there anymore, only they copies to ```fastcgi_params.old ``` and ```nginx.conf.old ``` were there.

Again, I did not create the .old files myself, nor did I remove the original file.

**Comment by davenaylor** [comment]
I ran the update today and immediately tried to restart nginx but that failed die to a missing `nginx.conf`.  Weird I thought but true enough it was gone.  All I had was `nginx.conf.old`.  I renamed it back to `nginx.conf` but I then hit the `fascgi_params` issue, the same as @ddelaey.

**Comment by MattyLB** [comment]
I don't know if this is related - but after my upgrade to 3.3.1 on Ubuntu
Trusty, I get this error related to my nginx config and I have not enabled
redis on any site, nor have I manually changed my nginx files for several
weeks and they worked perfectly through several versions until 3.3.1.
Afraid to upgrade to 3.3.2 until I get this figured out ...

>root@ip-172-00-00-00:~# nginx -t
>nginx: [emerg] unknown "srcache_fetch_status" variable
>nginx: configuration file /etc/nginx/nginx.conf test failed
>root@ip-172-31-28-36:~# ee update

I'll move it to the forums if it's not related to this open thread and how
the upgrade script is backing up the nginx.conf file and creating a new one
that has issues.

**Comment by harshadyeola** [comment]
@ddelaey 

I have confirmed this bug. and will befixing it right away.
Sorry for inconvinience.

**Comment by ddelaey** [comment]
@harshadyeola 
Thank you very much for the quick reaction, highly appreciated.
I've upgraded to 3.3.3 and did not see any issues.

**Comment by MattyLB** [comment]
YES! Confirmed as fixed for my issue reported above as well. Thank you!
