### ISSUE TITLE
Installation of stack and site under different users

### ISSUE THREAD

**Issue by perffaith** [rtCamp/easyengine#594]
I installed stack under root. Then tried to install site under regular user:
ee site create site.com --wpfc
Creation of DB failed.

ee site delete site.com --no-prompt
Deleting Database, None, user None
Error occured while deleting database

**Comment by perffaith** [comment]
Only --files flags works:
ee site delete site.com --files

Plus I deleted configs from
/etc/nginx/sites-enabled
/etc/nginx/sites-available

But when I try to create site with the same name I get:
site *** already exists

So how to manually delete site?

**Comment by brennentsmith** [comment]
You need to run the respective ee commands with sudo (or directly as root or a user with equiv. permissions). 

If you are determined for some reason to not run these with root perms, make sure the user you are using has permissions to connect to mysql and modify /var/www/ and /etc/nginx/sites-enabled/ directories. It also needs to be able to execute upstart commands (e.g. service nginx reload)

You can check the permissions for the directories via `ls -al` and mysql via `mysqladmin ping`.

**Comment by perffaith** [comment]
I run commands under root.
http://community.rtcamp.com/t/how-to-manually-delete-site/4904
