### ISSUE TITLE
How about an option for simply setting up a blank site?

### ISSUE THREAD

**Issue by MACscr** [rtCamp/easyengine#595]
As in no wordpress at all, it just sets up a new "virtualhost" for a new site. Your tool is pretty nice and I think would be beneficial for not WP sites as well that still could benefit from the account creation aspects.

**Comment by w33zy** [comment]
Are you referring to these existing commands

    ee site create example.com --html     # create example.com for static/html sites
    ee site create example.com --php      # create example.com with php support
    ee site create example.com --mysql    # create example.com with php & mysql support

**Comment by MACscr** [comment]
LOL. Thanks! I havent used it yet and I looked over the docs and didnt see that. This is great!

**Comment by w33zy** [comment]
That's OK, you can go ahead and close this issue. 

Also please checkout http://docs.rtcamp.com/easyengine/commands/ for more info
