### ISSUE TITLE
LOG: Connection refused while connecting to upstream

### ISSUE THREAD

**Issue by QROkes** [rtCamp/easyengine#596]
Nginx log file is full of this error:

[error] 3118#0: *7639 connect() failed (111: Connection refused) while connecting to upstream, client: 54.85.74.183, server: qrokes.com, request: "GET /anyfile.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:8000", host: "mydomain.com" 

My sites are woking just fine, but the log file is getting a lof of errors. Seems like Easyengine is not configuring nginx backend (127.0.0.1).

My site is: wpsubdir multisite, redis & hhvm.

**Comment by harshadyeola** [comment]
@QROkes 
Please check if your `hhvm` is running as this errors might be bcoz your hhvm is failed and php5-fpm is running as backup. 
Btw please create support ticket on community forum (http://community.rtcamp.com/c/easyengine) we will provide you support there.

for now i am closing this ticket.

**Comment by QROkes** [comment]
Actually, I'm not looking for support.
I´ve been just testing EE in some AWS instances (fresh installations) and most of the times I get this error in my logs.
Thats why I think its a bug.
