### ISSUE TITLE
Why are Nginx FastCGI Caching and Redis Object Caching mutually exclusive?

### ISSUE THREAD

**Issue by clifgriffin** [rtCamp/easyengine#602]
Redis is primarily useful for WP admin, FastCGI caching is primarily useful for frontend. 

Why do I have to choose between the two when creating a site?

**Comment by rahul286** [comment]
`--wpredis` uses redis for full page caching (fastcgi alternative) as well as object-caching.

**Comment by clifgriffin** [comment]
@rahul286 Ah ha, very interesting.  I had no idea that was a possibility. Thanks :)

**Comment by rahul286** [comment]
@clifgriffin I can understand. Many people are having similar questions/confusion. 

I am really clueless at the moment as how to explain this. We have written about it many places but as it is an unexpected a good feature, it seems very few people were ready for it.

**Comment by clifgriffin** [comment]
@rahul286 Yes, frankly I've found some of the documentation to be worded in confusing ways.  I've had to dig through it myself to understand how it works.

**Comment by rahul286** [comment]
@clifgriffin it will be really helpful if you can give document URL you have read. I will try to improve it over the weekend.
