### ISSUE TITLE
Setting up database ... Oops Something went wrong !!

### ISSUE THREAD

**Issue by anboto** [rtCamp/easyengine#610]
In Ubuntu 14.04.3 fresh installation and with the last version of ee, 3.3.5, there is an error with database (tried two times after purging any Mysql/MariaDB, Nginx and PHP/HHVM package):
Adding repository for MySQL, please wait...
Updating apt-cache, please wait...
Fixing missing GPG keys, please wait...
Installing packages, please wait...
Downloading MySQLTuner           [Done]
Reload : mysql     [OK]
Running pre-update checks, please wait...
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Downloading Wordpress 		[Done]
Setting up database		Oops Something went wrong !!

It throws with single and multi site, I used hhvm and pagespeed flag. The GPG key for MariaDB does not work, I added it manually. I think it is very silly thing, in the last stage of the process and so frustrating.

Anyone has any idea of how can I skip this error and start tasting EasyEngine? Thanks in advance.

**Comment by iam404** [comment]
could you please verify mysql credentials at `/etc/mysql/conf.d/my.cnf` are correct .
Also please verify if you could access mysql using command :

`mysql`

or if not root by `sudo mysql`

**Comment by anboto** [comment]
Good point 404man, I had some connection problem with the mysql socket, I am looking how to fix it, anyway MariaDBs GPG auto signing could be broken. Cheers.

**Comment by iam404** [comment]
Hii @anboto 

Please continue the discussion at - http://community.rtcamp.com/c/easyengine/

You can create a ticket related above issue .

**Comment by anboto** [comment]
Fixed database issue and realized that haven't no-common ports fully-opened on AWS, there were in Ubuntu but not in EC2, now I can connect in admin tools and think will too in GPG Key Server (cos also added 11371 port). So no new discussion needed! Many thanks for fast and good assistance, and congrats for your work, its just amazing!

**Comment by harshadyeola** [comment]
@anboto 

As your issue is fixed. I will close this issue.
