### ISSUE TITLE
Installing EasyEngine Fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by Sebguer** [rtCamp/easyengine#611]
Seems to be having issues installing psutil.

AttributeError: 'DummyFile' object has no attribute 'errors'
[ Thu Sep  3 20:49:46 EDT 2015 ] Unable to install EasyEngine, exit status  1
Traceback (most recent call last):
  File "/usr/local/bin/ee", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: psutil

output of: tail /var/log/ee/install.log

Installed /usr/local/lib/python3.4/dist-packages/sh-1.11-py3.4.egg
Searching for psutil
Reading https://pypi.python.org/simple/psutil/
Best match: psutil 3.2.1
Downloading https://pypi.python.org/packages/source/p/psutil/psutil-3.2.1.tar.gz#md5=a308816e735021fd4bf6aa561725c1aa
Processing psutil-3.2.1.tar.gz
Writing /tmp/easy_install-nq0b5ss_/psutil-3.2.1/setup.cfg
Running psutil-3.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-nq0b5ss_/psutil-3.2.1/egg-dist-tmp-pvbfyj6n

**Comment by screamolic** [comment]
i got same problem here..

**Comment by harshadyeola** [comment]
Confirmed ! looks like psutil package is broken.

**Comment by harshadyeola** [comment]
Quick solution for above issue 

```apt-get install python3-pip && pip3 install psutil```

We will fix this asap .

**Comment by screamolic** [comment]
another problem

Running pre-update checks, please wait...
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading Wordpress           [Done]
Setting up database             [Done]
Installing plugin nginx-helper, please wait...
Reload : nginx     [Failed]
Oops Something went wrong !!
Calling cleanup actions ...
Reload : nginx     [OK]
service nginx reload failed. check issues with `nginx -t` command.
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

**Comment by harshadyeola** [comment]
@screamolic 

can you give me output for `nginx -t`

**Comment by screamolic** [comment]
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by harshadyeola** [comment]
@screamolic 

can you please check with 
```ee stack purge --nginx && ee stack install --nginx```

**Comment by screamolic** [comment]
root@vultr:~# ee stack purge --nginx && ee stack install --nginx
Are you sure you to want to purge from server along with their configuration packages,
Any answer other than "yes" will be stop this operation :yes
Purging packages, please wait...
Successfully purged packages
Adding repository for NGINX, please wait...
Updating apt-cache, please wait...
Installing packages, please wait...
Reload : nginx     [OK]
HTTP Auth User Name: easyengine
HTTP Auth Password : 40rj5X
Successfully installed packages

**Comment by harshadyeola** [comment]
@screamolic 

can you try to create site now ? ``` ee site create example.com --wp``

**Comment by screamolic** [comment]
its w0rk,,,  

Running pre-update checks, please wait...
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading Wordpress           [Done]
Setting up database             [Done]
Installing plugin nginx-helper, please wait...
Reload : nginx     [OK]
WordPress admin user : admin2
WordPress admin user password : momon22
Successfully created site http://example.com

**Comment by screamolic** [comment]
s0, y0u want t0 update it ???
