### ISSUE TITLE
Help me! I can't install "stack"

### ISSUE THREAD

**Issue by bina4404** [rtCamp/easyengine#620]
root@vultr:~# ee stack install --nginx --php --mysql --postfix --wpcli --phpmyadmin --utils --admin
Adding repository for MySQL, please wait...
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
Updating apt-cache, please wait...
Oops Something went wrong!!
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
root@vultr:~# ee stack install --nginx --php --mysql --postfix --phpmyadmin --utils --admin
Adding repository for MySQL, please wait...
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
Updating apt-cache, please wait...
Oops Something went wrong!!
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

file ee.log

Ign http://download.opensuse.org  Translation-en_US
Hit http://archive.ubuntu.com trusty-updates/main Translation-en
Ign http://download.opensuse.org  Translation-en
Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
Err http://mirror.aarnet.edu.au trusty/main amd64 Packages
  404  Not Found [IP: 202.158.214.106 80]
Err http://mirror.aarnet.edu.au trusty/main i386 Packages
  404  Not Found [IP: 202.158.214.106 80]
Ign http://mirror.aarnet.edu.au trusty/main Translation-en_US
Ign http://archive.ubuntu.com trusty/main Translation-en_US
Ign http://archive.ubuntu.com trusty/universe Translation-en_US
Ign http://mirror.aarnet.edu.au trusty/main Translation-en
Fetched 69.0 kB in 5s (11.7 kB/s)
2015-09-20 02:06:50,443 (INFO) ee : [94m[91mOops Something went wrong!![0m
2015-09-20 02:06:50,443 (ERROR) ee : [91mCheck logs for reason `tail /var/log/ee/ee.log` & Try Again!!![0m

**Comment by harshadyeola** [comment]
This issue related to #618
