### ISSUE TITLE
wp-cron.php

### ISSUE THREAD

**Issue by evertsemeijn** [rtCamp/easyengine#622]
Just noticed an empty wp-cron.php is saved in home each time the cron runs. Could this be related to EE?
![screen shot 2015-09-22 at 10 20 54](https://cloud.githubusercontent.com/assets/26558/10013830/1c6ed11e-6115-11e5-9b78-ea95cb6b1806.png)

**Comment by harshadyeola** [comment]
@evertsemeijn 

EasyEngine does not configure any cron with WordPress. So this is not related to EasyEngine.
Please use Community forum for the discussions. (http://community.rtcamp.com/c/easyengine)
