### ISSUE TITLE
NGINX - mainline version from nginx.org

### ISSUE THREAD

**Issue by perroud** [rtCamp/easyengine#623]
Hello, guys.
Please, use the mainline version of NGINX instead of OpenSUSE repository:

from "variables.py"

    # EasyEngine stack installation varibales
    # Nginx repo and packages
    if ee_platform_codename == 'precise':
        ee_nginx_repo = ("deb http://download.opensuse.org/repositories/home:"
                         "/rtCamp:/EasyEngine/xUbuntu_12.04/ /")
    elif ee_platform_codename == 'trusty':
        ee_nginx_repo = ("deb http://download.opensuse.org/repositories/home:"
                         "/rtCamp:/EasyEngine/xUbuntu_14.04/ /")
    elif ee_platform_codename == 'wheezy':
        ee_nginx_repo = ("deb http://download.opensuse.org/repositories/home:"
                         "/rtCamp:/EasyEngine/Debian_7.0/ /")
    elif ee_platform_codename == 'jessie':
        ee_nginx_repo = ("deb http://download.opensuse.org/repositories/home:"
                         "/rtCamp:/EasyEngine/Debian_8.0/ /")

Official NGINX repository:
http://nginx.org/en/linux_packages.html#mainline

**Comment by gau1991** [comment]
Hello @perroud ,
Thanks for valuable suggestion. We build our Nginx with some custom modules which are not available with Nginx official ppa. So, if you use these PPA then some of functionality of WPFC, Redis sites will not work properly and you may face issue with you site.

**Comment by codxse** [comment]
any update about HTTP/2 ?

**Comment by PascaleBeier** [comment]
@codxse We were also concerned about HTTP/2 not being available in stable, but anyways:

1. Latest IE still doesn't support it (http://caniuse.com/#feat=http2)
2. Mainline is merged into stable anyways at a later moment

So let's just wait the few month :3
