### ISSUE TITLE
Add optional support for php 7

### ISSUE THREAD

**Issue by ichpen** [rtCamp/easyengine#626]
Really nice to have support for PHP 7 even in RC form. Already a PPA available for it.

**Comment by gau1991** [comment]
Hi @ichpen , 
PHP 7 is not stable yet. Its not advised to run it on production server. We will add PHP 7 support with PHP 5.6 to PHP 7 migration once stable PHP 7 will be available.

**Comment by ichpen** [comment]
I know, I was suggesting a - - develop or - - experimental flag is added to ee to pull the latest devel or rc release. Not just php but other modules also inc nginx. Just a suggestion

**Comment by lukechilds** [comment]
Is there a timeline for this now PHP 7 is fully released?

https://github.com/php/php-src/releases/tag/php-7.0.0

**Comment by gau1991** [comment]
Hello all.
We are still waiting for Ondrej Suri to built packages for stable PHP 7, As EasyEngine is depends upon his PHP repo.
Ref : https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0/+packages

**Comment by lukechilds** [comment]
Good to know, thanks.

**Comment by gagomap** [comment]
Thanks :D

**Comment by andremacola** [comment]
Ondrej Suri already updated his repo with php 7

**Comment by kklemen** [comment]
Any news on php7 with easy engine?

**Comment by lukechilds** [comment]
Looks like they're waiting for some bugs to get ironed out. https://github.com/EasyEngine/easyengine/issues/651#issuecomment-162216348

I'd imagine when Ondrej Suri supports PHP 7.0.1 EasyEngine will add support.

**Comment by robrecord** [comment]
I've just broken my production install because somehow "php" in apt-get now means "php7.0" in all cases; fpm and cli included. So really wishing for this support. Thanks. 

---
Rob Record
+44 (0)7535 271502  |  robrecord.com

**Comment by jponsen** [comment]
Any news on PHP7 support?

**Comment by MattyLB** [comment]
Only news I've seen from the php-src github group is that release 7.0 is
buggy and all the major fixes and improvements are slated for a v7.1
release but I don't know the anticipated release date for that. Check their
open issues on github. 7.01 might even be suitable for a go on EE as well.

**Comment by MattyLB** [comment]
Btw, looks like the OpenSSL issues will be resolved in 7.1 so if you're
concerned with encryption, might want to hold out for that.

**Comment by cdiscrete** [comment]
I would vote for PHP7 support (experimental at least).
Tried php7 on development environmental and everything is fine.

**Comment by MattyLB** [comment]
PHP 7.02 seems pretty stable. Sounds like there is already a solution in
the works to allow us to choose 5.6x or 7.x so hopefully we'll see
something soon. Beta or otherwise!

+1
