### ISSUE TITLE
hhvm seems not working 

### ISSUE THREAD

**Issue by tamimibrahim** [rtCamp/easyengine#629]
I have setup a site using easy engine using this command 
```
ee site create xyz.mysite.com --php --hhvm

```
Then when I echoed phpinfo() from index of that site hhvm not seems to be working. Am I doing anything wrong?

**Comment by ldashdixon** [comment]
Good catch!  I'm seeing the same problem with one of my installations.  EasyEngine claims it's running, but accord to the phpinfo, it does not appear to be so.

**Comment by iam404** [comment]
Hello @tamimibrahim 
Could you please check if your HHVM is running .
We checked on new server and could not replicate the issue.
```--php --hhvm``` is working fine at our end.
For any further query please use our support forum http://community.rtcamp.com/c/easyengine .
