### ISSUE TITLE
EasyEngine should set redis.conf parameters

### ISSUE THREAD

**Issue by zorrobyte** [rtCamp/easyengine#630]
By default, redis uses a maxmemory of 0 (unlimited) and maxmemory-policy "noeviction" which is bad behavior:
noeviction: return errors when the memory limit was reached and the client is trying to execute commands that could result in more memory to be used (most write commands, but DEL and a few more exceptions).

Instead, why not set the maxmemory based on the available system memory (a switch statement in Python could do) and set maxmemory-policy to something recommended like:
allkeys-lru: evict keys trying to remove the less recently used (LRU) keys first, in order to make space for the new data added.

**Comment by iam404** [comment]
With fresh installation of redis server with EasyEngine, 

`maxmemory` will be set to 20% of system memory

`maxmemory-policy` will be set to `volatile-lru`

**Comment by zorrobyte** [comment]
volatile-lru: evict keys trying to remove the less recently used (LRU) keys first, but only among keys that have an expire set, in order to make space for the new data added.

Did you integrate expiry into your Nginx helper plugin? If not, the cache is going to fill and no data will be evicted.
