### ISSUE TITLE
error in --phpredisadmin argument description

### ISSUE THREAD

**Issue by 2autunni** [rtCamp/easyengine#633]
EasyEngine v3.3.10

command **ee stack** prints 
>usage: ee stack (command) [options]
> ...
> --pagespeed      Install Pagespeed
>  --redis          Install Redis
> --phpredisadmin  Install Redis
> ....

instead  *--phpredisadmin  Install phpRedisAdmin*

**Comment by iam404** [comment]
PR merged https://github.com/rtCamp/easyengine/pull/634
