### ISSUE TITLE
 EasyEngine version ?

### ISSUE THREAD

**Issue by gagomap** [rtCamp/easyengine#640]
Hi,
I have updated EE version from 3.3.10 to 3.3.12 but when i use command "curl - I mysite.com", it show "X-Powered-By: EasyEngine 3.3.10"

What is EE version correct ?

**Comment by harshadyeola** [comment]
@gagomap 

We are not able to reproduce this issue. Please check your EasyEngine version with command ```ee -v```

**Comment by gagomap** [comment]
This is my result. It show EasyEngine v3.3.13
```bash
root@vps: ee -v
EasyEngine v3.3.13
Copyright (c) 2015 rtCamp Solutions Pvt. Ltd.
```
But when i use curl command, it show EasyEngine 3.3.10
``bash
root@vps: curl -I dautu365.com
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 17 Nov 2015 06:39:24 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: PHPSESSID=6ibj7m29nmukpk5bold8re73l0; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Pingback: http://dautu365.com/xmlrpc.php
Link: <http://dautu365.com/>; rel=shortlink
X-SRCache-Fetch-Status: MISS
X-SRCache-Store-Status: BYPASS
X-Powered-By: EasyEngine 3.3.10
```
