### ISSUE TITLE
FAQ says "EasyEngine v3 supports all Ubuntu Distro ( till its end of Life) and Debian 7" but readme "Ubuntu 12.04 & 14.04"

### ISSUE THREAD

**Issue by nextgenthemes** [rtCamp/easyengine#641]
FAQ says "EasyEngine v3 supports all Ubuntu Distro ( till its end of Life) and Debian 7" but readme "Ubuntu 12.04 & 14.04"

http://docs.rtcamp.com/easyengine/faq.html
https://github.com/rtCamp/easyengine/blob/master/README.md

What is the truth here?

**Comment by gagomap** [comment]
They mean Long Term Support version.

**Comment by harshadyeola** [comment]
@nextgenthemes 
Thanks for pointing the mistake. Updated the faq to match with README.
