### ISSUE TITLE
Feature request: Include Let's encrypt

### ISSUE THREAD

**Issue by NilsNojje** [rtCamp/easyengine#643]
It would be nice if EE would have the ability to setup https/tls using Le's Encrypt when creating (or modifying) a host.

**Comment by karlhaworth** [comment]
Duplicate.
https://github.com/rtCamp/easyengine/issues/376
https://github.com/rtCamp/easyengine/issues/559

**Comment by gau1991** [comment]
Duplicate of #376 

letsencrypt.org - already on roadmap.
