### ISSUE TITLE
FTP Solution

### ISSUE THREAD

**Issue by angelcosta** [rtCamp/easyengine#73]
Would it be possible to add and ftp solution? Editting themes and plugins online is kind of difficult.

**Comment by cinghaman** [comment]
Hi, I followed the above command but when i sftp on filezilla i get 
Disconnected: No supported authentication methods available (server sent: publickey)

I have an amazon e2 instance with ubuntu setup (i can ssh to the instance from my machine)

**Comment by janiosarmento** [comment]
You have to edit `/etc/passwd` and modify the shell for user www-data. 

You have to modify the last value from:

`/usr/sbin/nologin`

to:

`/bin/bash`

**Comment by cinghaman** [comment]
i have this in my passwd file 
www-data:x:33:33:www-data:/var/www:/usr/bin/bash

**Comment by janiosarmento** [comment]
I am sorry. I didn't realize you mentioned an Amazon EC2 instance. 

Their security standards are quite different, and you'll need a `.pem` file containing your credentials to access the server. I'm not used to EC2, thus I can't be of any help.

Sorry for wasting your time. :(

**Comment by cinghaman** [comment]
no worries mate
I do have a .pem file on my local machine downloaded from EC2, and this allows me to access my instance through ssh, but when i try to sftp it (with www-data as user) it says public key authenetication fail. so not sure where i am going wrong

**Comment by karlhaworth** [comment]
Is the SSH key in /var/www/.ssh? Additionally you should check the permissions on the authorized_keys file. Linux is very picky on those permissions.

**Comment by cinghaman** [comment]
karl, on my local or the server?

**Comment by karlhaworth** [comment]
Server. That error on the public key makes me believe that your SSH key is not properly set on the remote machine. I have dealt with that before and have seen the same error.

**Comment by cinghaman** [comment]
the file is empty

**Comment by karlhaworth** [comment]
There is a community for EasyEngine that is better to discuss these topics for future reference... That authorized key file needs to have your public key that was generated from your local workstation, where you'd be connecting from. Unless you're using a password for SSH, then that's a different topic... If you're unsure about setting up the authorized_key file to use SSH keys, [check here](https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2). You need to have the keys in the .ssh folder of all your users that will be logging in.

**Comment by cinghaman** [comment]
thanks
