### ISSUE TITLE
Forget PMA password & id

### ISSUE THREAD

**Issue by deprito** [rtCamp/easyengine#82]
Hey, i have some troblem. I forget the password for login to PMA. Is that possible for me reset my pma password?
Thanks

**Comment by irthos** [comment]
Having trouble with auth in phpmyadmin. tried using the user/pass from wp-config.php and from .my.cnf, neither works. Is there a way to reset?

**Comment by rippler** [comment]
Guys please use community forums, a lot of people receive these Github *bug* notifications.

**Comment by Jdesk** [comment]
how about root db access - for schema - dbs including sqllitedb - etc.
